"use client";
import { useVisionBridge } from "@/lib/workspace/useVisionBridge";

import React, { useState, useRef, useEffect } from "react";
import { applyPreviewNonce } from "@/lib/workspace/previewPolicy";
import { GeneratedAppPackage } from "@/lib/orchestrator/appGenerator";
import { 
  RefreshCw, 
  ExternalLink, 
  Code2, 
  Eye, 
  Sparkles, 
  MousePointerClick, 
  Layers, 
  Check, 
  X,
  Loader2
} from "lucide-react";

export interface InspectedElement {
  tag: string;
  id?: string;
  className?: string;
  text: string;
  selector: string;
  section?: string;
  top?: number;
}

interface DynamicMultiLayerSandboxProps {
  appPackage: GeneratedAppPackage;
  onShowToast?: (msg: string) => void;
  selectedElement?: InspectedElement | null;
  onSelectElement?: (el: InspectedElement | null) => void;
  standalone?: boolean;
  projectId?: string;
  missionId?: string;
  onRequestChange?: (prompt: string) => Promise<boolean>;
  isApplyingChange?: boolean;
  changeFeedback?: string;
}

/**
 * DynamicMultiLayerSandbox — Enterprise Visual Studio with Lovable-Style Inspector
 *
 * Renders the generated app.html directly inside an interactive <iframe srcDoc>.
 * Features Visual Element Inspector for targeted modifications (button, card, header).
 */
export function DynamicMultiLayerSandbox({
  appPackage,
  onShowToast,
  selectedElement,
  onSelectElement,
  standalone = false,
  projectId,
  missionId,
  onRequestChange,
  isApplyingChange = false,
  changeFeedback,
}: DynamicMultiLayerSandboxProps) {
  const [view, setView] = useState<"preview" | "html">("preview");
  const hasBackend = appPackage.sourceFiles.some(file => file.path === 'devkiller.runtime.json') ||
    (appPackage.sourceFiles.some(file=>file.path==='src/app/page.tsx') && appPackage.sourceFiles.some(file=>/^supabase\/migrations\/.*\.sql$/.test(file.path)));
  const [backendUrl, setBackendUrl] = useState('');
  const [backendError, setBackendError] = useState('');
  const backendRevision = hasBackend ? JSON.stringify(appPackage.sourceFiles) : '';
  useEffect(() => {
    if (!hasBackend || !missionId) return;
    let cancelled = false;
    setBackendUrl(''); setBackendError('');
    void fetch('/api/runtime', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({missionId})})
      .then(async response => { const data=await response.json(); if(!response.ok) throw new Error(data.error); if(!cancelled) setBackendUrl(data.url); })
      .catch(error => { if(!cancelled) setBackendError(error.message || 'Backend unavailable.'); });
    return () => {cancelled=true;};
  }, [hasBackend, missionId, backendRevision]);
  const [isInspectorActive, setIsInspectorActive] = useState(false);
  const [elementPrompt, setElementPrompt] = useState("");
  const elementInputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => {
    if (selectedElement && isInspectorActive) elementInputRef.current?.focus({ preventScroll: true });
  }, [selectedElement, isInspectorActive]);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  useVisionBridge(iframeRef,missionId);
  const [previewNonce, setPreviewNonce] = useState('');
  useEffect(() => { setPreviewNonce(crypto.randomUUID().replaceAll('-', '')); }, []);

  // Locate the HTML artifact generated by the AI
  const htmlFile = appPackage.sourceFiles.find(
    (f) => f.name === "app.html" || f.language === "html"
  );

  const rawHtmlContent = htmlFile?.content || null;

  const bundlePreviewDocument = (html: string) => {
    let bundled = html;
    const byPath = new Map(appPackage.sourceFiles.map(file => [file.path.replaceAll("\\", "/"), file]));
    const htmlPath = (htmlFile?.path || htmlFile?.name || "index.html").replaceAll("\\", "/");
    const base = htmlPath.includes("/") ? htmlPath.slice(0, htmlPath.lastIndexOf("/") + 1) : "";
    const resolve = (reference: string) => {
      const parts = `${base}${reference}`.split("/"); const normalized: string[] = [];
      for (const part of parts) { if (!part || part === ".") continue; if (part === "..") normalized.pop(); else normalized.push(part); }
      return normalized.join("/");
    };
    bundled = bundled.replace(/<link\b([^>]*?)href=["']([^"']+\.css)["']([^>]*)>/gi, (tag, before, reference, after) => {
      const file = byPath.get(resolve(reference)); if (!file) return tag;
      return `<style data-devkiller-bundled="${reference}">${file.content.replace(/<\/style/gi, "<\\/style")}</style>`;
    });
    bundled = bundled.replace(/<script\b([^>]*?)src=["']([^"']+\.js)["']([^>]*)><\/script>/gi, (tag, before, reference) => {
      const entry = byPath.get(resolve(reference)); if (!entry) return tag;
      const imports: string[] = []; let entryCode = entry.content.replace(/import\s+\{[^}]+\}\s+from\s+["']([^"']+)["'];?/g, (_statement, importedReference) => { const imported = byPath.get(resolve(importedReference)); if (imported) imports.push(imported.content.replace(/\bexport\s+/g, "")); return ""; });
      const code = `${imports.join("\n")}\n${entryCode}`.replace(/<\/script/gi, "<\\/script");
      return `<script type="module" data-devkiller-bundled="${reference}">${code}</script>`;
    });
    return bundled;
  };

  // Listen to postMessage from the iframe inspector script
  useEffect(() => {
    const handleMessage = (e: MessageEvent) => {
      if (e.source === iframeRef.current?.contentWindow && isInspectorActive && e.data && e.data.type === "DEVKILLER_INSPECT_ELEMENT") {
        setElementPrompt("");
        const elData: InspectedElement = e.data.element;
        if (onSelectElement) {
          onSelectElement(elData);
        }
        if (onShowToast) {
          onShowToast(`Selected ${elData.tag.toLowerCase()} element: "${elData.text.slice(0, 24)}"`);
        }
      }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, [onSelectElement, onShowToast, isInspectorActive]);

  // Inject Lovable-style interactive inspector script when inspector is enabled
  const getInjectedHtml = (html: string) => {
    if (!isInspectorActive) return html;

    const inspectorScript = `
      <style id="devkiller-inspector-css">
        .dk-inspect-hover {
          outline: 2px dashed #FF4B72 !important;
          outline-offset: 2px !important;
          cursor: crosshair !important;
          background-color: rgba(255, 75, 114, 0.08) !important;
          transition: outline 0.1s ease !important;
        }
        .dk-inspect-selected {
          outline: 2px solid #10B981 !important;
          outline-offset: 2px !important;
          background-color: rgba(16, 185, 129, 0.12) !important;
        }
      </style>
      <script id="devkiller-inspector-js">
        (function() {
          let currentHover = null;
          let currentSelected = null;

          document.addEventListener('mouseover', function(e) {
            if (currentHover && currentHover !== currentSelected) {
              currentHover.classList.remove('dk-inspect-hover');
            }
            if (e.target && e.target !== document.body && e.target !== document.documentElement) {
              currentHover = e.target;
              if (currentHover !== currentSelected) {
                currentHover.classList.add('dk-inspect-hover');
              }
            }
          }, true);

          document.addEventListener('mouseout', function(e) {
            if (currentHover && currentHover !== currentSelected) {
              currentHover.classList.remove('dk-inspect-hover');
            }
            currentHover = null;
          }, true);

          document.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation();

            const target = e.target;
            if (!target) return;

            if (currentSelected) {
              currentSelected.classList.remove('dk-inspect-selected');
            }
            currentSelected = target;
            currentSelected.classList.add('dk-inspect-selected');

            // Determine element description and section
            const tag = target.tagName.toUpperCase();
            const id = target.id || '';
            const className = target.className ? String(target.className) : '';
            const text = (target.innerText || target.value || target.placeholder || '').trim().slice(0, 80);
            
            // Guess section
            const closestSection = target.closest('section, header, footer, nav, form, .card, div[id], div[class*="section"]');
            const sectionName = closestSection ? (closestSection.id || closestSection.className || closestSection.tagName) : '';

            // Compute CSS selector
            const parts = [];
            let node = target;
            while (node && node.nodeType === 1) {
              if (node.id) { parts.unshift('#' + CSS.escape(node.id)); break; }
              const siblings = node.parentElement ? Array.from(node.parentElement.children).filter(s => s.tagName === node.tagName) : [node];
              parts.unshift(node.tagName.toLowerCase() + ':nth-of-type(' + (siblings.indexOf(node) + 1) + ')');
              node = node.parentElement;
            }
            const selector = parts.join(' > ');

            window.parent.postMessage({
              type: 'DEVKILLER_INSPECT_ELEMENT',
              element: {
                tag: tag,
                id: id,
                className: className,
                text: text || tag,
                selector: selector,
                section: sectionName
                ,top: target.getBoundingClientRect().bottom
              }
            }, '*');
          }, true);
        })();
      </script>
    `;

    if (html.includes("</body>")) {
      return html.replace("</body>", `${inspectorScript}</body>`);
    }
    return html + inspectorScript;
  };

  const handleRefresh = () => {
    if (iframeRef.current) {
      const iframe = iframeRef.current;
      const content = iframe.srcdoc;
      iframe.srcdoc = "";
      setTimeout(() => {
        iframe.srcdoc = content;
        if (onShowToast) onShowToast("Preview reloaded successfully!");
      }, 50);
    }
  };

  // State: Source files still being compiled
  if (hasBackend) return <div className={standalone ? 'fixed inset-0 bg-white' : 'space-y-3'}>
    {!standalone && <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-3 text-sm"><span>Isolated backend preview</span><a href={`/sandbox/live?project=${encodeURIComponent(missionId || projectId || '')}`} target="_blank" rel="noopener noreferrer" className="text-rose-500">New Tab</a></div>}
    {backendUrl ? <iframe ref={iframeRef} title={appPackage.appTitle} src={backendUrl} sandbox="allow-scripts allow-forms allow-same-origin allow-downloads" className={standalone ? 'h-full w-full border-0' : 'h-[75vh] min-h-[520px] w-full rounded-xl border border-slate-200 bg-white'} /> : <p role="status" className="p-6 text-sm text-slate-600">{backendError || (!missionId ? 'Mission identity is missing.' : 'Starting isolated backend…')}</p>}
    {!standalone && <p className="text-xs text-slate-500">Use Edit app for backend changes. Visual element selection is currently available for static previews only.</p>}
  </div>;
  if (appPackage.sourceFiles.length === 0) {
    return (
      <div className="rounded-3xl border border-slate-800 bg-[#0B0F19] flex flex-col items-center justify-center py-20 px-6 space-y-6 shadow-2xl animate-in fade-in duration-300">
        <div className="relative flex items-center justify-center">
          <div className="w-16 h-16 border-4 border-rose-500/20 border-t-[#FF4B72] rounded-full animate-spin" />
          <Sparkles className="w-6 h-6 text-[#FF4B72] absolute animate-pulse" />
        </div>
        <div className="text-center space-y-3 max-w-md w-full">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-rose-500/10 border border-rose-500/30 text-rose-400 text-xs font-mono font-bold uppercase tracking-wider">
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
            <span>Synthesizing Sandbox Runtime</span>
          </div>
          <h3 className="text-xl font-black text-white">{appPackage.appTitle}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">
            Forge (Full-Stack Engineer) and Iris (Experience Designer) are compiling the application workspace.
          </p>
          
          {/* Animated Compilation Progress Bar */}
          <div className="w-full bg-slate-900 rounded-full h-2 overflow-hidden border border-slate-800 my-2">
            <div className="bg-gradient-to-r from-[#FF4B72] to-emerald-400 h-full rounded-full animate-pulse transition-all duration-500 w-4/5" />
          </div>

          <p className="text-slate-500 text-[11px]">
            ⚡ Real-time synthesis via LLM engine. Automatically renders upon arrival.
          </p>
        </div>
      </div>
    );
  }

  // State: HTML not found in source files
  if (!rawHtmlContent) {
    return (
      <div className="rounded-3xl border border-amber-900/50 bg-amber-950/30 p-8 flex flex-col items-center justify-center space-y-4">
        <div className="w-12 h-12 rounded-2xl bg-amber-900/40 flex items-center justify-center">
          <Code2 className="w-6 h-6 text-amber-400" />
        </div>
        <div className="text-center space-y-1">
          <p className="text-amber-200 font-bold text-sm">HTML Sandbox Preview Unavailable</p>
          <p className="text-amber-400/70 text-xs">The project files were compiled but did not include app.html.</p>
          <p className="text-slate-400 text-xs">Check the generated React component in the &quot;Source Code&quot; tab.</p>
        </div>
      </div>
    );
  }

  // Editor-only scrollbar treatment; exported and standalone app design stays intact.
  const scrollStyle = standalone ? "" : `<style data-devkiller-scrollbars>
    html { scrollbar-gutter: stable; }
    * { scrollbar-width: thin; scrollbar-color: #ff4b7270 transparent; }
    ::-webkit-scrollbar { width: 5px; height: 5px; }
    ::-webkit-scrollbar-track { background: transparent; }
    ::-webkit-scrollbar-thumb { background: #ff4b7270; border-radius: 99px; }
    ::-webkit-scrollbar-thumb:hover { background: #ff4b72; }
  </style>`;
  const bundledDocument = getInjectedHtml(bundlePreviewDocument(rawHtmlContent));
  const styledDocument = bundledDocument.includes("</head>") ? bundledDocument.replace("</head>", `${scrollStyle}</head>`) : `${scrollStyle}${bundledDocument}`;
  const finalHtmlDoc = applyPreviewNonce(styledDocument, previewNonce);

  if (standalone) return (
    <iframe ref={iframeRef} key={previewNonce} srcDoc={finalHtmlDoc}
      sandbox="allow-scripts allow-forms allow-same-origin allow-modals allow-downloads"
      title={appPackage.appTitle}
      className="fixed inset-0 h-[100dvh] w-full border-0 bg-white" />
  );

  return (
    <div className="space-y-3 animate-in fade-in duration-300">
      {/* Sandbox Navigation & Control Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white rounded-2xl px-4 py-3 border border-slate-200 shadow-sm">
        <div className="flex items-center gap-2">
          <span className="ml-3 text-xs font-mono text-slate-700 font-bold hidden sm:inline truncate max-w-xs">
            {appPackage.appTitle}
          </span>

        </div>

        <div className="flex items-center gap-2 flex-wrap">
          {/* Lovable-Style Visual Inspector Toggle Button */}
          <button
            onClick={() => {
              const next = !isInspectorActive;
              setIsInspectorActive(next);
              if (!next && onSelectElement) {
                onSelectElement(null);
              }
              if (onShowToast) {
                onShowToast(next ? "Visual Inspector enabled! Click on any element inside the app to edit." : "Visual Inspector disabled.");
              }
            }}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer border ${
              isInspectorActive
                ? "bg-[#FF4B72] text-white border-rose-400 shadow-md shadow-rose-500/25 ring-2 ring-rose-400/30 animate-pulse"
                : "bg-white hover:bg-slate-50 text-slate-600 hover:text-slate-900 border-slate-200"
            }`}
            title="Click to inspect and select specific buttons, sections or elements to edit (Lovable style)"
          >
            <MousePointerClick className="w-3.5 h-3.5" />
            <span>{isInspectorActive ? "Inspector: ON" : "Visual Edit"}</span>
          </button>

          {/* Toggle Preview / HTML Source */}
          <div className="flex rounded-xl border border-slate-200 overflow-hidden text-xs bg-slate-50">
            <button
              onClick={() => setView("preview")}
              className={`px-3 py-1.5 flex items-center gap-1.5 cursor-pointer transition-colors ${
                view === "preview" ? "bg-white text-slate-900 font-bold shadow-sm" : "text-slate-500 hover:text-slate-900"
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Preview</span>
            </button>
            <button
              onClick={() => setView("html")}
              className={`px-3 py-1.5 flex items-center gap-1.5 cursor-pointer transition-colors ${
                view === "html" ? "bg-white text-slate-900 font-bold shadow-sm" : "text-slate-500 hover:text-slate-900"
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>HTML</span>
            </button>
          </div>

          {/* Open in Standalone Window */}
          <a
            href={missionId || projectId ? `/sandbox/live?project=${encodeURIComponent(missionId || projectId || '')}` : "/sandbox/live"}
            target="_blank"
            rel="noopener noreferrer"
            className="px-3 py-1.5 rounded-xl bg-white hover:bg-slate-50 text-slate-600 hover:text-slate-900 text-xs font-semibold flex items-center gap-1.5 transition-colors border border-slate-200"
            title="Open application in standalone full-window tab"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">New Tab</span>
          </a>

          {/* Reload Preview */}
          <button
            onClick={handleRefresh}
            className="p-1.5 rounded-xl text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors cursor-pointer border border-slate-200"
            title="Reload sandbox preview"
          >
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Inspector Active Helper Banner */}
      {isInspectorActive && (
        <div className="bg-rose-500/10 border border-rose-500/30 rounded-xl px-4 py-2.5 flex items-center justify-between gap-3 text-xs text-rose-300 animate-in fade-in duration-200">
          <div className="flex items-center gap-2">
            <MousePointerClick className="w-4 h-4 text-[#FF4B72] shrink-0" />
            <span>
              <strong>Visual Inspector Active:</strong> Hover and click any button, header, card, or text in the preview below to focus your edit prompt on it.
            </span>
          </div>
          {selectedElement && (
            <div className="flex items-center gap-2 bg-emerald-950/60 border border-emerald-500/40 text-emerald-300 px-2.5 py-1 rounded-lg text-[11px] font-mono font-bold">
              <span>🎯 &lt;{selectedElement.tag.toLowerCase()}&gt; &quot;{selectedElement.text.slice(0, 18)}&quot;</span>
              <button
                onClick={() => onSelectElement && onSelectElement(null)}
                className="hover:text-white cursor-pointer ml-1"
                title="Clear selection"
              >
                <X className="w-3 h-3" />
              </button>
            </div>
          )}
        </div>
      )}

      {/* PREVIEW: iframe with AI-generated HTML */}
      {view === "preview" && (
        <div className="relative rounded-2xl overflow-hidden border border-slate-200 shadow-sm bg-white flex-1 w-full" style={{ minHeight: "520px", height: "calc(100vh - 200px)" }}>
          {isInspectorActive && selectedElement && onRequestChange && (
            <form role="dialog" aria-label="Edit selected element" onSubmit={async e => {
              e.preventDefault();
              if (!elementPrompt.trim() || isApplyingChange) return;
              if (await onRequestChange(elementPrompt.trim())) { setElementPrompt(""); setIsInspectorActive(false); }
            }} className="element-edit-popover absolute z-20 right-3 w-[260px] max-w-[calc(100%-24px)] rounded-xl border border-rose-200 bg-white p-3 shadow-lg" style={{ top: `clamp(12px, ${Number.isFinite(selectedElement.top) ? selectedElement.top : 12}px, calc(100% - 200px))` }}>
              <div className="flex items-center justify-between gap-2 text-xs font-semibold text-slate-900">
                <span className="truncate">Edit {selectedElement.tag.toLowerCase()}</span>
                <button type="button" aria-label="Close element editor" disabled={isApplyingChange} onClick={() => onSelectElement?.(null)}><X className="h-4 w-4" /></button>
              </div>
              <p className="my-1.5 truncate text-[11px] text-slate-500">{selectedElement.text}</p>
              <textarea ref={elementInputRef} aria-label="Requested element change" value={elementPrompt} onChange={e => setElementPrompt(e.target.value)} disabled={isApplyingChange} placeholder="What should change here?" className="block w-full resize-none rounded-lg border border-slate-200 p-2 text-xs leading-5 text-slate-900 focus:outline-[#FF4B72]" rows={2} />
              <button disabled={isApplyingChange || !elementPrompt.trim()} className="mt-2 w-full rounded-lg bg-[#FF4B72] px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-50">{isApplyingChange ? "Applying and checking…" : "Apply change"}</button>
              {changeFeedback && <p role="status" className="mt-2 max-h-20 overflow-auto text-xs text-slate-600">{changeFeedback}</p>}
            </form>
          )}
          <iframe
            ref={iframeRef}
            key={previewNonce}
            srcDoc={finalHtmlDoc}
            sandbox="allow-scripts allow-forms allow-same-origin allow-modals allow-downloads"
            title={`Sandbox: ${appPackage.appTitle}`}
            className="w-full h-full bg-white"
            style={{ border: "none", minHeight: "520px", height: "100%" }}
          />
        </div>
      )}

      {/* HTML SOURCE VIEW */}
      {view === "html" && (
        <div className="rounded-2xl overflow-hidden border border-slate-800 bg-[#090D16] flex-1 w-full" style={{ minHeight: "520px", height: "calc(100vh - 200px)" }}>
          <div className="overflow-auto h-full p-5">
            <pre className="text-xs font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
              {rawHtmlContent}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
