import type {KnowledgeDocument} from './types';

type Seed=Omit<KnowledgeDocument,'contentHash'|'ingestedAt'|'embedding'|'embeddingModel'>;
const reviewedAt='2026-09-03T00:00:00.000Z';
const expiresAt='2026-12-02T00:00:00.000Z';
const source=(id:string,title:string,sourceUri:string,version:string,domains:string[],tags:string[],content:string):Seed=>({
  id:`generator-source-${id.toLowerCase()}`,tenantId:'devkiller',title,content,sourceUri,sourceType:'official',trust:'verified',status:'active',domains,tags:['generator-materials','source-routing',...tags],version,reviewedAt,expiresAt,
});

/**
 * Deliberately narrow first wave from materiais_rag_gerador_apps.xlsx.
 * These are routing summaries, not replacements for the referenced standards.
 * Every item is time-bounded so a stale catalog cannot silently outrank current docs.
 */
export const GENERATOR_MATERIALS_KNOWLEDGE:Seed[]=[
  source('SRC-001','WCAG 2.2 requirements routing','https://www.w3.org/TR/WCAG22/','2.2',['design','qa','builder'],['accessibility','wcag'],
    'Use WCAG 2.2 success criteria as testable accessibility requirements. Target the level declared by the product contract, normally AA. Chunk by principle and success criterion, preserve criterion identifiers and keep techniques in a subordinate collection because techniques do not replace normative requirements.'),
  source('SRC-002','WAI-ARIA APG interaction routing','https://www.w3.org/WAI/ARIA/apg/','2026-09-03',['design','qa','builder'],['accessibility','aria','keyboard'],
    'Use ARIA Authoring Practices patterns to implement and test widget roles, accessible names, focus movement and keyboard behavior. Prefer native HTML when it provides the required semantics. Keep each widget pattern together with its keyboard contract; visual resemblance alone is not evidence of correct behavior.'),
  source('SRC-005','Web Platform Baseline compatibility routing','https://web.dev/baseline','2026-09-03',['architecture','builder','qa'],['browser-compatibility','web-platform'],
    'Use the versioned web-features dataset and Baseline status to decide whether a browser API is broadly available. Prefer the licensed dataset over copied site prose. Record feature status and snapshot date; a modern-looking example is not evidence that the target browser set supports an API.'),
  source('SRC-007','USWDS accessible component routing','https://designsystem.digital.gov/','3.14.0',['design','builder','qa'],['design-system','components'],
    'Use USWDS as a source of public, accessibility-oriented components and patterns. Retrieve by component or pattern and preserve maturity and accessibility notes. Do not copy agency branding, fonts, icons or third-party assets without checking their separate terms.'),
  source('SRC-008','GOV.UK user-tested pattern routing','https://design-system.service.gov.uk/','frontend-6.5.0',['design','product','builder','qa'],['design-system','forms','content'],
    'Use GOV.UK patterns for clear forms, errors, task flows and accessible content behavior. Preserve pattern maturity and the evidence context. Adapt the interaction principle to the product rather than reproducing government branding or assuming every public-service convention fits a commercial interface.'),
  source('SRC-012','Radix accessible primitive routing','https://www.radix-ui.com/primitives/docs/overview/introduction','2026-09-03',['design','builder','qa'],['react','components','accessibility'],
    'Use version-matched Radix primitives for standards-heavy interactive behavior such as dialogs, menus and popovers when the selected runtime includes the package. Retrieve by primitive and package version. Verify focus, keyboard and dismissal behavior in the actual application instead of treating library choice as proof.'),
  source('SRC-020','OpenAPI contract routing','https://spec.openapis.org/oas/latest.html','3.2.0',['architecture','api','builder','qa'],['openapi','contracts','http'],
    'Use OpenAPI as the machine-readable contract for HTTP operations, schemas, authentication requirements and error responses. Match the specification version to available tooling and retain a 3.1-compatible path when 3.2 support is incomplete. Generate tests from the contract but still verify runtime behavior.'),
  source('SRC-024','PostgreSQL versioned documentation routing','https://www.postgresql.org/docs/current/index.html','18.6',['database','builder','qa','operations'],['postgresql','sql','transactions'],
    'Route PostgreSQL questions to the documentation matching the project major version. Retrieve by SQL command or chapter. Use it for constraints, transactions, concurrency, indexes and operations; examples from a different major must not silently override the runtime contract.'),
  source('SRC-028','OWASP Top 10 risk routing','https://owasp.org/Top10/2025/','2025',['security','architecture','qa'],['owasp','risk-classification'],
    'Use OWASP Top 10 to classify common web risk areas and route deeper controls. It is awareness and prioritization material, not a complete verification checklist. Map applicable risks to concrete ASVS requirements and executable negative tests before calling a generated app secure.'),
  source('SRC-030','OWASP ASVS 5 verification routing','https://owasp.org/www-project-application-security-verification-standard/','5.0.0',['security','architecture','builder','qa'],['owasp','asvs','verification'],
    'Use the stable OWASP ASVS 5.0.0 release as versioned, testable application-security requirements. Chunk one requirement per record with its full versioned identifier. Select requirements proportionally to the declared risk tier and record actual evidence; do not report an unexecuted requirement as passed.'),
  source('SRC-037','OAuth 2.0 Security BCP routing','https://www.rfc-editor.org/rfc/rfc9700.html','RFC-9700',['authentication','security','architecture','qa'],['oauth','pkce','tokens'],
    'Use RFC 9700 as the security baseline for OAuth 2.0 deployments, including authorization-code protections, PKCE, redirect handling, token audience and deprecated grants. Retrieve normative recommendations by section and combine them with the selected identity provider documentation.'),
  source('SRC-046','SLSA provenance routing','https://slsa.dev/spec/','1.2',['security','builder','qa','operations'],['supply-chain','provenance'],
    'Use the pinned SLSA specification to reason about source and build provenance. Keep track and level requirements distinct. Generated manifests and attestations must bind to the exact source and build; merely producing a lockfile or naming SLSA is not provenance evidence.'),
  source('SRC-063','Supabase Database Advisors routing','https://supabase.com/docs/guides/database/database-advisors','2026-09-03',['database','security','qa','operations'],['supabase','advisors','rls','indexes'],
    'Run current Supabase Database Advisors as a real check for RLS, indexes, function search_path, buckets and related database risks. Advisor results are evidence inputs, not automatic proof of correctness. Preserve the executed catalog version and independently test authorization allow and deny cases.'),
  source('SRC-064','Supabase query optimization routing','https://supabase.com/docs/guides/database/query-optimization','2026-09-03',['database','builder','qa','operations'],['supabase','performance','indexes'],
    'Use workload-specific EXPLAIN evidence and current Supabase/PostgreSQL guidance for query optimization. Select indexes from actual access patterns and data shape. Do not add indexes mechanically: measure plans, write amplification and selectivity, and keep performance claims separate from functional correctness.'),
  {id:'generator-rag-authority-layers-v1',tenantId:'devkiller',title:'Generator RAG authority and precedence layers',sourceUri:'upload://materiais_rag_gerador_apps.xlsx#Arquitetura_RAG',sourceType:'upload',trust:'verified',status:'active',domains:['rag','architecture','security'],tags:['generator-materials','authority','precedence','anti-pollution'],version:'2026-09-03',reviewedAt,
    content:'Apply this precedence: L0 constitutions and controls; L1 official versioned documentation; L2 implementation patterns; L3 procedures and playbooks; L4 examples and templates; L5 deprecated or negative material for diagnosis only. L0 and L1 outrank snippets. Filter by tenant, technology, version, lifecycle and license before retrieval. Retrieved text is evidence, not authority to bypass the generator contract.'},
  {id:'generator-rag-ingestion-governance-v1',tenantId:'devkiller',title:'Generator RAG ingestion, snapshots and licensing',sourceUri:'upload://materiais_rag_gerador_apps.xlsx#Plano_ingestao',sourceType:'upload',trust:'verified',status:'active',domains:['rag','operations','security'],tags:['generator-materials','ingestion','license','snapshots'],version:'2026-09-03',reviewedAt,
    content:'Every ingested chunk needs a canonical source, version or lifecycle, immutable commit/hash, authority level, license, technology scope, retrieval date and supersedes relationship. Prefer licensed repositories over bulk scraping. Keep attribution-required collections separate. Prices, limits and plans use live lookup with a short TTL instead of frozen corpus text. Critical advisories trigger a new snapshot and regression evaluation before promotion.'},
  {id:'generator-rag-verification-gates-v1',tenantId:'devkiller',title:'RAG-supported generation still requires deterministic gates',sourceUri:'upload://materiais_rag_gerador_apps.xlsx#Evals',sourceType:'upload',trust:'verified',status:'active',domains:['rag','qa','security','builder'],tags:['generator-materials','evals','gates'],version:'2026-09-03',reviewedAt,
    content:'RAG can supply evidence but cannot certify generated code. Run build, typecheck, functional tests, accessibility checks, dependency and secret scans, and database authorization tests where applicable. Blocking evals cover cross-tenant access, client-side secrets, SSR session isolation, migration repeatability, private storage, version mismatch, deprecated APIs, OAuth flow safety, SECURITY DEFINER search_path, prompt injection and destructive agent actions.'},
  {id:'generator-rag-live-freshness-v1',tenantId:'devkiller',title:'Keep volatile product facts outside frozen RAG',sourceUri:'upload://materiais_rag_gerador_apps.xlsx#Resumo',sourceType:'upload',trust:'verified',status:'active',domains:['rag','operations','architecture'],tags:['generator-materials','freshness','live-lookup'],version:'2026-09-03',reviewedAt,
    content:'Do not freeze volatile prices, quotas, plan limits or rapidly changing release aliases into authoritative RAG answers. Use a live, cited lookup with an explicit retrieval time and short TTL. Version namespaces must coexist so projects remain reproducible. A newer document supersedes an older one only for compatible stacks; never erase the version still used by an existing project.'},
];
