// Authored summaries, not copied repository prompts. Source-verified guidance
// is distinct from a remedy reproduced against a DevKiller candidate.
export const RECOVERY_PLAYBOOKS = [
  {id:'diagnose-before-edit',title:'Reproduce a broken UI before patching',source:'https://www.dyad.sh/docs/guides/debugging',scope:'application',content:'For a broken control, capture the action, expected result, observed result and exact sanitized error. Reproduce the smallest journey before proposing a focused patch; rerun that journey and adjacent working behavior. A vague failure report is not a confirmed cause. Source documentation recommends concrete errors, frequent testing and undo. This guidance does not prove any specific DevKiller repair.'},
  {id:'preview-startup',title:'Distinguish preview startup from application defects',source:'https://www.dyad.sh/docs/guides/previewing',scope:'application',content:'When a preview stays blank or loads slowly, inspect runtime and dependency installation messages first. Distinguish page refresh from server restart. Check readiness and asset loading before rewriting source. Do not restart a shared server or unrelated active mission automatically. Source guidance notes initial dependency installation can take time; it does not establish that every blank page is an infrastructure problem.'},
  {id:'missing-import',title:'Missing npm import and cross-origin detector limitations',source:'https://github.com/firecrawl/open-lovable/blob/69bd93bae7a9c97ef989eb70aabe6797fb3dac89/components/HMRErrorDetector.tsx',scope:'application',content:'The inspected component parses Vite failed-import overlays and extracts the base npm package, including scoped names. Relative imports require checking paths and filenames, not installing a similarly named package. Confirm manifest, lockfile, registry identity and installed version before changing dependencies. Cross-origin iframe inspection may fail; an inaccessible overlay is not evidence of a healthy app. Detection is a clue, not automatic permission to install arbitrary packages. This recipe is source-reviewed, not validated for every generated stack.'},
  {id:'false-clean-report',title:'Never treat a placeholder error endpoint as validation',source:'https://github.com/firecrawl/open-lovable/blob/69bd93bae7a9c97ef989eb70aabe6797fb3dac89/app/api/check-vite-errors/route.ts',scope:'platform',content:'At the inspected commit, this endpoint is explicitly a stub that returns success with an empty error list. Do not use it as evidence of a successful compilation or browser journey. Require a recorded execution, candidate identity, command or browser outcome, and explicit unavailable status when no check ran. This is an audited antipattern, not a claim about all Open Lovable validation or its future versions.'},
  {id:'bounded-refinement',title:'Bound repair iterations and preserve concrete critique',source:'https://docs.openhands.dev/sdk/guides/iterative-refinement',scope:'platform',content:'The documented example separates a worker from critique and imposes an iteration limit. For DevKiller, bind each finding to a candidate and a reproducer; retry only when new evidence or a changed patch can address it. Route missing execution capability to verification rather than another rewrite. Stop on repeated unchanged failure or exhausted budget. A model-assigned quality score is not a substitute for passing tests. This adaptation is guidance, not a validated claim of autonomous recovery.'},
  {id:'persist-operation-state',title:'Persist execution separately from delivered application',source:'https://docs.openhands.dev/sdk/guides/convo-persistence',scope:'platform',content:'OpenHands documents persisted base execution state and incremental event history. DevKiller should likewise distinguish a revision operation from the last approved delivery: a failed revision must not erase that delivery or make a different browser infer a first build. Restore only matching mission identities and reconcile authoritative timestamps. Never publish raw state containing credentials. This is an architectural adaptation, not a promise that two unrelated persistence systems have identical semantics.'},
] as const;
