import type { KnowledgeDocument } from './types';
type Seed = Omit<KnowledgeDocument,'contentHash'|'ingestedAt'|'embedding'|'embeddingModel'>;
const common = {tenantId:'public',sourceType:'official' as const,trust:'verified' as const,status:'active' as const,version:'1.0.0',reviewedAt:'2026-09-03T00:00:00.000Z',expiresAt:'2027-03-03T00:00:00.000Z'};
// Reviewed summaries, not copied articles, automatic incident promotions, or proof of execution.
export const RELIABILITY_KNOWLEDGE: Seed[] = [
 {...common,id:'postgres-concurrency-retry-v1',title:'PostgreSQL: concurrent inventory updates and serialization retries',domains:['database','builder','qa','recovery'],tags:['supabase','postgresql','concurrency','transactions'],sourceUri:'https://www.postgresql.org/docs/current/transaction-iso.html',content:'PostgreSQL Read Committed SELECT sees a statement snapshot, not a reservation on future stock. Concurrent UPDATE waits for a conflicting writer and rechecks its WHERE predicate on the updated row. Applied design guidance: decrement inventory with a guarded UPDATE WHERE stock >= requested quantity, check affected rows, and create the order in the same transaction. A browser read followed by an unconditional write is insufficient. Serializable transactions may fail and require retrying the whole transaction, not only the last statement. Apply bounded retries with a documented failure outcome; do not retry every SQL error indiscriminately. Validate simultaneous last-unit requests and rollback behavior with independent database connections. This guidance does not prove a generated migration or concurrency test passed.'},
 {...common,id:'supabase-ssr-cache-isolation-v1',title:'Supabase SSR: session refresh and shared cache isolation',domains:['authentication','security','builder','qa'],tags:['supabase','sessions','cache','ssr'],sourceUri:'https://supabase.com/docs/guides/auth/server-side/advanced-guide',content:'Supabase warns that caching responses containing refreshed Set-Cookie headers can sign another visitor into the wrong session. Disable ISR for routes that handle authentication or refresh sessions. Apply private, no-store to authenticated responses and verify the actual CDN cache policy. Create the server Supabase client inside each request, not in a shared module-level variable carrying user state. With @supabase/ssr versions supporting cache headers in setAll, forward those headers as well as cookies. Applied validation guidance: test two independent users through the deployed proxy, inspect cache behavior, and verify refresh/logout without cross-user data. A missing initial session should show sign-in, not be reported as a database outage. This source does not certify the local app cookie namespace or production isolation.'},
 {...common,id:'canvas-cors-export-v1',title:'Canvas image export: CORS approval and tainted bitmap failures',domains:['design','builder','qa','recovery'],tags:['canvas','images','export','cors'],sourceUri:'https://developer.mozilla.org/en-US/docs/Web/HTML/How_to/CORS_enabled_image',content:'Drawing a foreign image without CORS approval taints the canvas. Reading pixels or exporting with toBlob or toDataURL can then throw SecurityError, even when the image displays correctly. Set the image crossOrigin mode before src and require an appropriate Access-Control-Allow-Origin response from the image server. Applied validation guidance: use a controlled same-origin asset or an approved CORS source, wait for successful image loading, and test the downloaded output, not only the preview. Show a clear recoverable error if export fails. Do not claim a successful download or silently omit a required brand image. Do not disable browser security to make the test pass. This browser rule alone does not validate image-generation permissions or visual quality.'},
];
