"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ModelControls } from './ModelControls';
import {FamilyAccess} from './FamilyAccess';
import { Home, RefreshCw, ShieldCheck } from 'lucide-react';
import { ADMIN_CHECKS, cacheEstimate } from '@/lib/admin/metrics';
type Note={check_id:string;state:string;note:string;updated_at?:string};
type Row={model:string;schema_name:string;calls:number;completed:number;active:number;usage_calls:number;cache_reporting_calls:number;input_tokens:string|null;output_tokens:string|null;cached_tokens:string|null;write_tokens:string|null;seconds:string|null};
type Overview={at:string;provider:Row[];missions:{status:string;count:number}[];notes:Note[];models:Record<string,string>;routing:boolean;cacheRouting:boolean};
const count=(n:unknown)=>n===null || n===undefined ? 'Unavailable' : Number(n).toLocaleString('en-US');
export function AdminDashboard(){
  const [data,setData]=useState<Overview|null>(null),[days,setDays]=useState(7),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
    fetch(`/api/admin/overview?days=${days}`,{cache:'no-store',signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result);}).catch(error=>{if(!controller.signal.aborted)setError(error.message || 'Unable to load data.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return ()=>controller.abort();
  },[days,refresh]);
  const calls=data?.provider.reduce((sum,row)=>sum+row.calls,0) || 0;
  return <main className="min-h-screen bg-[#FAF8F5] px-4 py-8 text-[#111420] sm:px-8">
    <div className="mx-auto max-w-6xl space-y-6">
      <header className="flex flex-wrap items-center justify-between gap-4">
        <div><Link href="/create" className="mb-4 inline-flex items-center gap-2 text-xs font-semibold text-slate-600 hover:text-rose-500"><Home className="h-3.5 w-3.5"/>App builder home</Link><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#FF4B72]">DevKiller · Owner administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Operations & quality</h1><p className="mt-2 text-sm text-slate-500">Real usage, explicit evidence, and the next improvements to validate.</p></div>
        <div className="flex flex-wrap items-center gap-2"><Link href="/create" className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700"><Home className="h-3.5 w-3.5"/>Home</Link><select aria-label="Reporting period" value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-xl border border-slate-200 bg-white p-2.5 text-xs">{[1,7,30].map(value=><option key={value} value={value}>Last {value} {value===1?'day':'days'}</option>)}</select><button disabled={loading} onClick={()=>setRefresh(value=>value+1)} className="flex items-center gap-2 rounded-xl bg-[#111420] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><RefreshCw className={`h-3 w-3 ${loading?'animate-spin':''}`}/>Refresh</button></div>
      </header>
      {error&&<p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error} Existing data, if shown, may be stale.</p>}
      {!data&&loading&&<p role="status" className="text-sm text-slate-500">Loading administration data…</p>}
      <ModelControls />
      <FamilyAccess />
      <section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-white p-5"><div><h2 className="text-sm font-bold">Generator quality lab</h2><p className="mt-1 text-xs text-slate-500">Fixed technical benchmarks for React builds, database isolation, browser checks and focused edits.</p></div><Link href="/admin/generator" className="rounded-xl bg-[#111420] px-4 py-2.5 text-xs font-semibold text-white">Open quality lab →</Link></section>
      {data&&<>
        <div className="grid gap-3 sm:grid-cols-3">{[
          ['Provider requests',String(calls),'Recorded requests, including repairs. Not the number of missions.'],
          ['Cache routing',data.cacheRouting?'Enabled':'Hint disabled','Provider automatic caching may still apply. Savings are not guaranteed.'],
          ['Model routing',data.routing?'Per-stage overrides':'Single configured model','Configuration only; no model or connectivity test is triggered here.'],
        ].map(([title,value,detail])=><section key={title} className="rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-rose-50/30 p-5"><p className="text-xs text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></section>)}</div>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold">Configured models</h2><div className="mt-4 grid gap-3 sm:grid-cols-4">{Object.entries(data.models).map(([role,model])=><div key={role} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{role}</p><p className="mt-1 break-all text-xs font-semibold">{model}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Historical usage below may include other models. These controls are read-only; changing a model requires a separate validated rollout.</p></section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
          <div className="p-5"><h2 className="text-base font-bold">Usage & cache evidence</h2><p className="mt-2 text-xs leading-5 text-slate-500">Recorded provider requests created in this period, across the installation. Replayed local responses are not counted as new calls. Missing provider usage remains unavailable.</p></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-slate-500"><tr>{['Model / task','Calls / completed','Input / output','Cache read / write','Usage / complete cache records','Avg. seconds','Est. input savings'].map(label=><th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{data.provider.map(row=>{
            const estimate=row.cache_reporting_calls===row.calls && /^gpt-5\.6(?:-|$)/.test(row.model) ? cacheEstimate(Number(row.input_tokens),row.cached_tokens===null?null:Number(row.cached_tokens),row.write_tokens===null?null:Number(row.write_tokens)) : null;
            return <tr key={row.model+row.schema_name} className="border-b border-slate-100 last:border-0"><td className="px-4 py-4 font-semibold">{row.model}<span className="mt-1 block font-normal text-slate-400">{row.schema_name}</span></td><td className="px-4">{row.calls} / {row.completed}</td><td className="px-4">{count(row.input_tokens)} / {count(row.output_tokens)}</td><td className="px-4">{count(row.cached_tokens)} / {count(row.write_tokens)}</td><td className="px-4">{row.usage_calls} / {row.cache_reporting_calls}</td><td className="px-4">{row.seconds ?? '—'}</td><td className="px-4 font-semibold">{estimate?`${estimate.percent.toFixed(1)}%`:'Insufficient data'}</td></tr>;
          })}</tbody></table>{!data.provider.length&&<p className="p-5 text-sm text-slate-500">No recorded requests in this period.</p>}</div>
          <details className="border-t border-slate-100 p-5 text-xs text-slate-500"><summary className="cursor-pointer font-semibold text-slate-800">How to evaluate savings correctly</summary><div className="mt-3 space-y-2 leading-6"><p>Input-only estimate for GPT-5.6: uncached tokens + cached tokens × 0.10 + cache-write tokens × 1.25, compared with processing all input at the normal rate. Negative savings mean cache writes outweighed reuse.</p><p>This is not your invoice or an experimental before/after result. It excludes output, tools, storage and infrastructure. Rates are assumptions; confirm current pricing before financial decisions. All calls in a row must report cache usage before an estimate appears.</p><p>For a real comparison, run the same briefs and quality gates, then compare total cost per approved mission, repair count and elapsed time. Duration here includes polling and persistence, not only model execution. Do not weaken QA to improve the numbers.</p><a href="https://developers.openai.com/api/docs/guides/prompt-caching" target="_blank" rel="noreferrer" className="text-rose-500 underline">OpenAI cache documentation</a></div></details>
        </section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold">Mission outcomes</h2><div className="mt-3 flex flex-wrap gap-2">{data.missions.map(item=><span key={item.status} className="rounded-lg bg-slate-50 px-3 py-2 text-xs">{item.status}: <strong>{item.count}</strong></span>)}</div><p className="mt-3 text-xs text-slate-500">Includes retained and discarded mission records. Mission creation date defines the period. No success percentage is inferred from unfinished missions.</p></section>
      </>}
      <section><h2 className="text-lg font-bold">Validation checklist & reminders</h2><p className="mt-1 text-xs leading-5 text-slate-500">Manual review records, saved to your account. “Verified” requires an evidence note; it is your assessment, not an automatic test result. No tests, paid calls or scheduled notifications run from this page.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{data&&ADMIN_CHECKS.map(item=><CheckCard key={item.id} item={item} initial={data.notes.find(note=>note.check_id===item.id)}/>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold">Engineering changes to validate</h2><p className="mt-2 text-xs leading-6 text-slate-500">Cache routing and usage reporting · syntax-aware unfinished-code checks · no-login/session-only foundation routing · repeated-failure stop · generated-app language contract.</p><p className="mt-2 text-xs leading-6 text-slate-400">Maintained implementation checklist, not a live deployment inventory. Model benchmarks, hosted File Search, image generation and Sandbox Agents remain separate experiments; this page does not enable them.</p></section>
      <footer className="flex flex-wrap items-center justify-between gap-2 text-[10px] text-slate-400"><span className="flex items-center gap-1"><ShieldCheck className="h-3 w-3"/>Restricted to the configured owner administrator</span><span>{data?`Data retrieved ${new Date(data.at).toLocaleString('en-US')}`:''}</span></footer>
    </div>
  </main>;
}
function CheckCard({item,initial}:{item:typeof ADMIN_CHECKS[number];initial?:Note}){
  const [state,setState]=useState(initial?.state || 'pending'),[note,setNote]=useState(initial?.note || ''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  async function save(){setSaving(true);setMessage('');try{const result=await fetch('/api/admin/overview',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,state,note})});const body=await result.json();if(!result.ok)throw new Error(body.error);setMessage('Saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save.');}finally{setSaving(false);}}
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-bold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{item.detail}</p><label className="mt-4 block text-[10px] font-semibold text-slate-500">Review status<select disabled={saving} value={state} onChange={e=>setState(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white p-2 text-xs"><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="verified">Verified manually</option></select></label><label className="mt-3 block text-[10px] font-semibold text-slate-500">Evidence / next action<textarea disabled={saving} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={3} placeholder="Test date, result, evidence location, or next action. Never enter secrets." className="mt-1 block w-full resize-y rounded-lg border border-slate-200 p-3 text-xs font-normal"/></label><div className="mt-3 flex items-center gap-3"><button onClick={save} disabled={saving} className="rounded-lg bg-[#111420] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save review'}</button><span role="status" className="text-xs text-slate-500">{message}</span></div></article>;
}
