'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,ShieldOff,ShieldCheck} from 'lucide-react';
type Member={id:string;email:string;name:string;role:string;accessEnabled:boolean;generatorEnabled:boolean;managedAiEnabled:boolean;budgetMicros:number|null;spentMicros:number;reservedMicros:number;activeRuns:number;revokedAt:string|null};
const money=(value:number)=>`$${(value/1e6).toFixed(2)}`;
export function FamilyAccess(){
  const [members,setMembers]=useState<Member[]>([]),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const response=await fetch('/api/admin/members',{cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error);setMembers(body.members);}catch(error){setError(error instanceof Error?error.message:'Unable to load access.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function toggle(member:Member){setBusy(member.id);setError('');try{const response=await fetch('/api/admin/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:member.id,accessEnabled:!member.accessEnabled})}),body=await response.json();if(!response.ok)throw new Error(body.error);await load();}catch(error){setError(error instanceof Error?error.message:'Unable to change access.');}finally{setBusy('');}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">Family tester access</h2><p className="mt-1 text-xs leading-5 text-slate-500">Separate accounts, private projects and a hard cumulative AI budget. Cutting a connection blocks the account immediately and stops its active local run.</p></div><button onClick={()=>void load()} disabled={loading} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-50"><RefreshCw className={`h-3 w-3 ${loading?'animate-spin':''}`}/>Refresh</button></div>
  {error&&<p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}
  <div className="mt-4 grid gap-3 md:grid-cols-2">{members.map(member=>{const remaining=member.budgetMicros===null?null:Math.max(0,member.budgetMicros-member.spentMicros-member.reservedMicros);return <article key={member.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold">{member.name}</h3><p className="mt-1 text-[11px] text-slate-500">{member.email}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${member.accessEnabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{member.accessEnabled?'Connected':'Access cut'}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-400">Budget remaining</dt><dd className="mt-1 font-bold">{remaining===null?'Owner managed':money(remaining)}</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-400">In progress</dt><dd className="mt-1 font-bold">{member.activeRuns}</dd></div></dl><p className="mt-3 text-[10px] leading-4 text-slate-500">App creation: {member.generatorEnabled?'enabled':'disabled'} · Owner image AI: {member.managedAiEnabled?'enabled':'disabled'} · spent {money(member.spentMicros)}{member.reservedMicros?` · held ${money(member.reservedMicros)}`:''}</p><button onClick={()=>void toggle(member)} disabled={busy===member.id} className={`mt-4 flex w-full items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-bold disabled:opacity-50 ${member.accessEnabled?'border border-rose-200 text-rose-600 hover:bg-rose-50':'bg-[#111420] text-white'}`}>{member.accessEnabled?<ShieldOff className="h-3.5 w-3.5"/>:<ShieldCheck className="h-3.5 w-3.5"/>}{busy===member.id?'Applying…':member.accessEnabled?'Cut connection':'Restore access'}</button></article>;})}</div>
  {!loading&&!members.length&&<p className="mt-4 text-xs text-slate-500">No tester accounts have been created yet.</p>}</section>;
}
