"use client";
import { useEffect,useState } from 'react';
import { MODEL_OPTIONS,POLICY_ROLES,type ModelPolicy } from '@/lib/admin/modelPolicy';
type Settings={current:{id:string;policy:ModelPolicy};history:{id:string;policy:ModelPolicy;created_at:string}[];checks:{model:string}[]};
const labels={product:'Product specialist',specialists:'Technical specialists',decision:'Final decision',build:'Build',qa:'Independent QA',repair:'Repair'};
export function ModelControls(){
 const [data,setData]=useState<Settings|null>(null),[policy,setPolicy]=useState<ModelPolicy|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(reset=true){const r=await fetch('/api/admin/models',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(reset)setPolicy(d.current.policy);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function action(body:{action:string;[key:string]:unknown}){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(body.action==='save');setMessage(body.action==='save'?'Saved for new missions only.':'Compatibility passed; app quality is not yet validated.');}catch(e){setMessage(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Model configuration · new missions</h2><p className="mt-2 text-xs leading-5 text-slate-500">Select → test → save. Existing missions retain their models. Sol is the premium-cost option; Luna is experimental. Tests check access and structured output, not app quality.</p>
 {policy&&data&&<><div className="mt-4 grid gap-3 sm:grid-cols-3">{POLICY_ROLES.map(role=><label key={role} className="text-xs font-semibold text-slate-600">{labels[role]}<select disabled={busy} value={policy[role]} onChange={e=>setPolicy({...policy,[role]:e.target.value as ModelPolicy[typeof role]})} className="mt-2 block w-full rounded-lg border border-slate-200 bg-white p-2 text-xs">{MODEL_OPTIONS.map(model=><option key={model}>{model}</option>)}</select></label>)}</div>
 <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>setPolicy({product:'gpt-5.6-luna',specialists:'gpt-5.6-terra',decision:'gpt-5.6-terra',build:'gpt-5.6-terra',qa:'gpt-5.6-terra',repair:'gpt-5.6-terra'})} className="rounded-lg border border-rose-200 px-3 py-2 text-xs text-rose-600">Experimental · Luna product only</button><button disabled={busy} onClick={()=>setPolicy(data.current.policy)} className="rounded-lg border px-3 py-2 text-xs">Discard draft</button></div>
 <p className="mt-4 text-xs text-slate-500">Each compatibility test makes one small paid API call, capped at 64 output tokens. Results expire after 24 hours.</p><div className="mt-3 flex flex-wrap gap-2">{[...new Set(Object.values(policy))].map(model=><button key={model} disabled={busy} onClick={()=>{if(window.confirm(`Run a small paid compatibility check for ${model}?`))void action({action:'test',model});}} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-50">{data.checks.some(c=>c.model===model)?'✓ Recheck':'Test'} {model}</button>)}</div>
 <button disabled={busy || Object.values(policy).some(model=>!data.checks.some(c=>c.model===model))} onClick={()=>{if(window.confirm('Apply to new missions? Cost and quality may change.'))void action({action:'save',policy,version:data.current.id});}} className="mt-4 rounded-lg bg-[#111420] px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Save for new missions</button>
 <details className="mt-4 text-xs"><summary className="cursor-pointer text-slate-500">History & restore</summary>{data.history.map(item=><div key={item.id} className="mt-3 rounded-lg bg-slate-50 p-3"><p>{new Date(item.created_at).toLocaleString('en-US')} · Version {item.id}</p><p className="mt-1 break-words text-slate-500">{POLICY_ROLES.map(role=>`${role}: ${item.policy[role]}`).join(' · ')}</p><button disabled={busy} className="mt-2 text-rose-500" onClick={()=>{setPolicy(item.policy);setMessage('Restored as draft. Test if needed, then save.');}}>Restore as draft</button></div>)}</details></>}
 <p role="status" className="mt-3 text-xs text-slate-500">{busy?'Working…':message}</p></section>;
}
