/** Authored product guidance. Numeric defaults below are DK heuristics, not claims of WCAG requirements. */
export const DESIGN_GUIDANCE_VERSION='2.0.0';
export const DESIGN_QUALITY_RULES=`
ART DIRECTION AND CRAFT — DEVKILLER v2
1. Choose a visual direction before implementing. Record a concise "Design direction" entry in the existing validationPlan: audience, primary task, tone, composition, typography roles, palette roles and one distinctive detail. Describe the selected direction, not hidden reasoning. Do not spend another model call on this. A simple functional scope does not mean careless visual design.
2. Design the main working surface, not a marketing page pasted above a form. An operational app opens on useful records and its primary action; its decorative heading must not push the task below the first viewport. A creator/editor gives most usable space to the artifact, with a compact toolbar and contextual inspector. A storefront prioritizes genuine product media, concise information and a clear reservation/cart path. A sports activation prioritizes brand recognition and one thumb-friendly next action. These are task principles, not mandatory features or fixed templates.
3. Make the chosen identity visible through at least two coordinated decisions: composition, typography contrast, image treatment, surface geometry or interaction details. A giant serif heading, random gradient, emoji, letter avatar or generic card grid alone is not art direction. Expressive, playful, editorial, technical or restrained styles are all valid when appropriate. Never copy DevKiller's palette into an unrelated app by default. Preserve an explicit requested minimalist style.
4. Define a small token system for canvas, surface, primary/secondary text, accent, border, spacing and radii. Use color deliberately: neutral foundations plus a controlled accent is a starting point, not a universal palette. Additional colors need semantic or brand roles. Avoid equally saturated competing blocks, excessive gradients, glow around every card and inconsistent rounding/shadows. Use separators or spacing instead of nesting a bordered card around every paragraph.
5. Typography has separate display and functional roles. As DK starting defaults use 14–16px readable interface text, 16px mobile form inputs, 12–13px secondary metadata and 20–32px working-screen headings; adapt to content, zoom and audience. Large expressive type belongs to a deliberate hero/artifact, not all labels and buttons. Use at most two type families, intentional weights, comfortable line-height and bounded text measure. Avoid global condensed italic, text blur/stroke, transform scaling and low-contrast tiny copy. Do not invent font availability: use installed/system fonts or permitted packaged assets, never forbidden remote font downloads.
6. Establish alignment and a consistent spacing scale, for example 4/8/12/16/24/32/48px. Related elements sit closer than separate groups. Layout adapts to content: split panels may stack or become drawers on mobile, not simply shrink. Test 390px and 1440px plus 320px/200% zoom reflow where practical. No clipped headings, hidden primary action or accidental page-wide horizontal scrolling. Dense tables may have their own labelled scrolling region.
7. Media is part of delivery, not a placeholder. When supplied or required, use genuine brand/product assets, preserve proportions, choose a deliberate crop, and verify loading in preview and export. Do not replace a required product photo with an initial letter, fake thumbnail or unconfigured image URL. If no asset is available, state the limitation or use a purposeful non-photographic composition when the brief allows it. Never add paid image generation automatically just for polish.
8. A coherent interaction system includes hover, keyboard focus, selected, loading, disabled, empty, error and success states. Choose one primary action per task region. Labels remain visible; buttons look actionable; data uses honest values. Use restrained 120–240ms feedback as a DK default, reserve image/loading space, and avoid layout jumps or decoration that blocks work. Respect reduced-motion preferences. Dialogs need initial focus, contained keyboard navigation, Escape dismissal and focus return.
9. Accessibility is a floor, not a visual style: WCAG AA normal text contrast at least 4.5:1, qualifying large text 3:1. WCAG 2.2 target-size minimum is 24x24 CSS pixels or the criterion's spacing/other exceptions; prefer comfortable 44px controls for primary mobile tasks as DK ergonomics guidance. Never use color alone for status. Test actual rendered colors, keyboard interaction and long content; token names alone are not evidence.
10. Review visual craft separately from functional correctness. Record observations for task hierarchy, identity, typography, spacing/density, media, interaction and responsive behavior with specific screen/component evidence. Missing screenshots or browser execution means pending verification, not defective source. Fix observable defects with a scoped patch; subjective stylistic alternatives are advisory, not an endless repair loop. Never claim "premium", "award-winning", a visual score or trend popularity from CSS existence or unexecuted checks. Research dated references only when trends are requested; summarize principles, never copy an entire site's distinctive design.
`;
