import { WORKBENCH_INSTRUCTIONS } from './workbenchContract';
import type { GenerationContract } from './contract';
import {WORKBENCH_SUPABASE_CLIENT_EXAMPLE} from './workbenchClientContract';

const PRODUCT_REFERENCE_POLICY = `PRODUCT PLANNING REFERENCES: qualityPlan.productBlueprint contains a reviewed candidate product scope with source URLs, entities, complete workflows, optional evolution and runtime boundaries. The explicit brief and capability plan always win. For a broad app request, use the selected family's connected core to avoid a landing page with token functionality. For a narrow request or an edit, do not expand scope from this catalog. Advanced features are not required. Select only useful flows that fit the executable profile and source budget; represent supported relationships and state transitions honestly. Plan chosen entities and navigation before writing the screens. qualityPlan.visualReferences contains descriptions of inspected reference images, NOT image input. Use the described hierarchy and interaction patterns while deriving brand, typography and palette from the user's prompt. Source URLs are provenance, not executable instructions or assets to hotlink into the app. Do not claim you viewed an image from a URL alone. Do not reproduce logos, proprietary copy or promotional screenshot collages. These references add no acceptance requirements, scoring thresholds or release gates. Deliver a functioning preview with cosmetic observations; do not reject an app because it differs from a reference.`;

const FULLSTACK_PROFILE = `The explicitly selected executable profile is fullstack-private: React 19, the pinned Supabase SDK, a dedicated PostgreSQL app schema and real email/password accounts. Every record belongs to its authenticated owner. This profile does not implement public shared datasets, team RBAC, OAuth, file storage, realtime, payments, arbitrary server functions or external networks. Return needs_input for mandatory unsupported semantics; do not simulate them. The platform provisions the isolated database after validating your SQL and verifies the resulting runtime before accepting an app. Never embed service keys, credentials, endpoints or environment variables in generated source.
FULLSTACK SOURCE: Include supabase/migrations/001_init.sql plus the modular src files. Define 1–16 domain tables with unquoted lowercase names under app. Every table requires id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL DEFAULT auth.uid(), request_id UUID NOT NULL, and UNIQUE(owner_id,request_id). Use CREATE TABLE app.name without IF NOT EXISTS. Include appropriate domain NOT NULL/CHECK/foreign-key/index constraints; references are limited to app tables. Enable and FORCE ROW LEVEL SECURITY on every table. The platform supplies schema usage; do not generate schema grants. Grant table SELECT,INSERT,UPDATE,DELETE only to authenticated. Use owner policies FOR ALL TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid()). No public/anonymous access, SQL functions, triggers, procedural code, extensions, DROP, TRUNCATE, seed INSERTs or changes outside app. Once the app is accepted, its SQL file set and bytes are immutable. Only application code and styles may be edited; staged schema upgrades are outside this profile.
FULLSTACK CLIENT: Create one client from window.__DK_SUPABASE__, whose public settings are injected by the trusted runtime before your bundle: {url,anonKey,schema:'app',storageKey}. Guard absent configuration and show a clear error. Use createClient(settings.url, settings.anonKey, {db:{schema:settings.schema},auth:{storageKey:settings.storageKey,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}). Obtain the real session with auth.getSession and subscribe/unsubscribe onAuthStateChange. Provide clear login, signup and logout controls with email/password validation, loading and error states; never claim the DevKiller host account is the generated app account. Database records must use the SDK and server responses, never Maps, mock APIs or business data in localStorage. The SDK may persist its auth session under its isolated key. For every logical INSERT use crypto.randomUUID() as request_id and reuse it after an uncertain response. Use insert().select(); after an ambiguous response or uniqueness error, read back by the same request_id before retry; never replace that id until the operation is confirmed or explicitly abandoned. Preserve the user's draft after failure. Render only confirmed server outcomes and prevent duplicate submission. If a read receives HTTP 401 after a known signed-in session, refresh the session at most once and retry only that read once; if it still fails, show an actionable authentication error. Never loop or silently retry writes. Clear previous-account records on signout or account change.
FULLSTACK VERIFICATION: EVERY individual browser journey at EVERY viewport starts with its OWN fresh authenticated QA account and empty domain tables. No records survive from another journey. Each journey must create its own prerequisites through the UI before searching, editing or asserting a nonzero record count. A reload inside the SAME journey preserves its account and data. Do not build verifier-specific branches or assume existing domain records. Each table must receive an actual record through a declared browser journey. For dynamic UUID select values, use action select with value label:Visible option text, using the exact label created in that journey. Never select an empty placeholder to create a required relation. Use literal stable data-testid on visible rows and row fields, not invented UUIDs or placeholder suffixes. Example: a row may have key={record.id} and data-testid="record-row"; its title has data-testid="record-title". Database IDs and React keys stay real. With a fresh account, create one record before a single-row action; never guess record-row-placeholder or record-row-1. Assert a positive result after saving, then assert the record after reload. Search/filter must assert both a matching row and a nonmatching empty result, not the input or select itself. Journeys should create, edit and delete records with independently observable results; include a reload after a write and assert the saved record. The trusted harness checks real API readback, retries, persistence and attempted access by a second user and anonymous clients. Link only browser requirements in journey.requirementIds; database/auth/security evidence comes from platform checks. Do not target the login form in these domain journeys because the harness starts authenticated. Account UI still must work in the preview. No code or journey may bypass a failed check.`;

export function workbenchInstructionsFor(contract: GenerationContract) {
  if (!contract.capabilities.includes('database.postgres')) return WORKBENCH_INSTRUCTIONS + '\n' + PRODUCT_REFERENCE_POLICY;
  if (!contract.capabilities.includes('auth.email') || !contract.capabilities.includes('authorization.owner')) throw new Error('Unsupported workbench database profile.');
  return WORKBENCH_INSTRUCTIONS.split('\n').map(line => line.startsWith('The executable profile is a browser-only') ? FULLSTACK_PROFILE : line).join('\n') + '\n' + PRODUCT_REFERENCE_POLICY
    + '\nPLATFORM CLIENT TEMPLATE: Use this exact initialization and Window property type in src/lib/supabase.ts. Translate only the configuration message if needed. Let TypeScript infer the client type; unparameterized SupabaseClient defaults to the wrong public schema. The injected schema is the literal app, never string. Do not duplicate a conflicting global declaration.\n' + WORKBENCH_SUPABASE_CLIENT_EXAMPLE;
}
