import { WORKBENCH_INSTRUCTIONS } from './workbenchContract';
import type { GenerationContract } from './contract';

const FULLSTACK_PROFILE = `The explicitly selected executable profile is fullstack-private: React 19, the pinned Supabase SDK, a dedicated PostgreSQL app schema and real email/password accounts. Every record belongs to its authenticated owner. This profile does not implement public shared datasets, team RBAC, OAuth, file storage, realtime, payments, arbitrary server functions or external networks. Return needs_input for mandatory unsupported semantics; do not simulate them. The platform provisions the isolated database after validating your SQL and verifies the resulting runtime before accepting an app. Never embed service keys, credentials, endpoints or environment variables in generated source.
FULLSTACK SOURCE: Include supabase/migrations/001_init.sql plus the modular src files. Define 1–16 domain tables with unquoted lowercase names under app. Every table requires id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL DEFAULT auth.uid(), request_id UUID NOT NULL, and UNIQUE(owner_id,request_id). Use CREATE TABLE app.name without IF NOT EXISTS. Include appropriate domain NOT NULL/CHECK/foreign-key/index constraints; references are limited to app tables. Enable and FORCE ROW LEVEL SECURITY on every table. The platform supplies schema usage; do not generate schema grants. Grant table SELECT,INSERT,UPDATE,DELETE only to authenticated. Use owner policies FOR ALL TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid()). No public/anonymous access, SQL functions, triggers, procedural code, extensions, DROP, TRUNCATE, seed INSERTs or changes outside app. Once the app is accepted, its SQL file set and bytes are immutable. Only application code and styles may be edited; staged schema upgrades are outside this profile.
FULLSTACK CLIENT: Create one client from window.__DK_SUPABASE__, whose public settings are injected by the trusted runtime before your bundle: {url,anonKey,schema:'app',storageKey}. Guard absent configuration and show a clear error. Use createClient(settings.url, settings.anonKey, {db:{schema:settings.schema},auth:{storageKey:settings.storageKey,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}). Obtain the real session with auth.getSession and subscribe/unsubscribe onAuthStateChange. Provide clear login, signup and logout controls with email/password validation, loading and error states; never claim the DevKiller host account is the generated app account. Database records must use the SDK and server responses, never Maps, mock APIs or business data in localStorage. The SDK may persist its auth session under its isolated key. For every logical INSERT use crypto.randomUUID() as request_id and reuse it after an uncertain response. Use insert().select(); after an ambiguous response or uniqueness error, read back by the same request_id before retry; never replace that id until the operation is confirmed or explicitly abandoned. Preserve the user's draft after failure. Render only confirmed server outcomes and prevent duplicate submission.
FULLSTACK VERIFICATION: Browser journeys start with a real authenticated QA session in a fresh account. Do not build verifier-specific branches or assume existing domain records. Each table must receive an actual record through a declared browser journey. Journeys should create, edit and delete records with independently observable results; include a reload after a write and assert the saved record. The trusted harness checks real API readback, retries, persistence and attempted access by a second user and anonymous clients. Link only browser requirements in journey.requirementIds; database/auth/security evidence comes from platform checks. Do not target the login form in these domain journeys because the harness starts authenticated. Account UI still must work in the preview. No code or journey may bypass a failed check.`;

export function workbenchInstructionsFor(contract: GenerationContract) {
  if (!contract.capabilities.includes('database.postgres')) return WORKBENCH_INSTRUCTIONS;
  if (!contract.capabilities.includes('auth.email') || !contract.capabilities.includes('authorization.owner')) throw new Error('Unsupported workbench database profile.');
  return WORKBENCH_INSTRUCTIONS.split('\n').map(line => line.startsWith('The executable profile is a browser-only') ? FULLSTACK_PROFILE : line).join('\n');
}
