'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowUp,Check,MousePointer2,Pause,Play,Coffee,ShoppingBag,Plus} from 'lucide-react';
import AuroraPreview from './AuroraPreview';
import {DEMO_DURATION, getDemoStage} from './demo-timeline';

import type {Locale} from '@/lib/tools/registry';
export default function CreateDemo({locale}:{locale:Locale}){
 const t=(a:string,b:string)=>locale==='pt'?b:a;
 const [time,setTime]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);
 const root=useRef<HTMLDivElement>(null),visible=useRef(true),elapsed=useRef(0);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(media.matches);change();media.addEventListener('change',change);const observer=new IntersectionObserver(entries=>{visible.current=entries[0].isIntersecting;});if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener('change',change);};},[]);
 useEffect(()=>{if(paused||reduced)return;let previous=performance.now();const timer=setInterval(()=>{const now=performance.now();const delta=Math.min(now-previous,250);previous=now;if(document.hidden||!visible.current)return;elapsed.current=(elapsed.current+delta)%DEMO_DURATION;setTime(elapsed.current);},80);return()=>clearInterval(timer);},[paused,reduced]);
 const ms=reduced?33000:time;const stage=getDemoStage(ms);
 const prompt=t('Build a café app with a menu, a cart and order tracking.','Crie um app de cafeteria com cardápio, carrinho e acompanhamento de pedidos.');
 const typed=prompt.slice(0,Math.floor(Math.max(0,ms-4400)/4800*prompt.length));
 const progress=Math.min(100,Math.max(0,Math.floor((ms-10500)/7600*100)));
 const phases=[t('Planning your app','Planejando seu app'),t('Designing the screens','Desenhando as telas'),t('Building the experience','Construindo a experiência'),t('Checking the details','Conferindo os detalhes')];
 const phase=Math.min(3,Math.floor(progress/25));const clicking=(ms>2800&&ms<3250)||(ms>9800&&ms<10200)||(ms>20700&&ms<21200);
 const cursorVisible=!reduced&&((ms>1500&&ms<3400)||(ms>9100&&ms<10400)||(ms>19500&&ms<21400));
 return <div ref={root} className={`dk-create-demo${paused?' is-paused':''}${reduced?' is-reduced':''}`}><div className={`dk-demo-window dk-demo-${stage}`} role="group" aria-label={t('Animated example: a café app goes from a typed request through planning, design, building and checks to a finished menu and order screen.','Exemplo animado: um pedido de app de cafeteria passa por planejamento, design, construção e revisão até mostrar cardápio e pedidos prontos.')}><div aria-hidden="true"><img className="dk-demo-logo" src="/tools-assets/dk.png" alt="" width="58" height="58"/><span className="dk-demo-workspace">DK Create <span>· {t('Your idea, taking shape','Sua ideia ganhando forma')}</span></span>
 <div className="dk-demo-scene dk-demo-intro-scene"><h2>{t('One idea. So many possibilities.','Uma ideia. Muitas possibilidades.')}</h2><div className="dk-swatches"><span/><span/><span/><span/></div><div className={`dk-demo-faux-button${clicking&&stage==='intro'?' is-clicked':''}`}>{t('Build an app','Criar aplicativo')}<ArrowUpRight size={16}/><MousePointer2 className={`dk-demo-cursor dk-target-cursor${cursorVisible?' is-visible':''}${clicking?' is-clicking':''}`} size={27} fill="#172034" stroke="white" strokeWidth={1.6}/></div></div>
 <div className="dk-demo-scene dk-demo-prompt-scene"><span className="dk-demo-kicker">{t('START WITH AN IDEA','COMECE COM UMA IDEIA')}</span><h3>{t('What would you like to build?','O que você quer construir?')}</h3><div className="dk-demo-chat"><p>{typed}<span className="dk-demo-caret"/></p><span className={`dk-demo-send${clicking&&stage==='prompt'?' is-clicked':''}`}><ArrowUp size={17}/><MousePointer2 className={`dk-demo-cursor dk-target-cursor${cursorVisible?' is-visible':''}${clicking?' is-clicking':''}`} size={27} fill="#172034" stroke="white" strokeWidth={1.6}/></span></div><small>{t('A few words. A whole new possibility.','Poucas palavras. Uma nova possibilidade.')}</small></div>
 <div className="dk-demo-scene dk-demo-building-scene"><span className="dk-demo-kicker">CAFÉ AURORA</span><h3>{t('A little closer to your idea.','Cada vez mais perto da sua ideia.')}</h3><div className="dk-demo-progress-label"><span>{phases[phase]}</span><strong>{progress}%</strong></div><div className="dk-demo-track"><span style={{width:progress+'%'}}/></div><div className="dk-demo-phases">{phases.map((name,i)=><div key={name} className={i<=phase?'is-active':''}><span>{i<phase?<Check size={12}/>:String(i+1).padStart(2,'0')}</span><small>{name}</small></div>)}</div></div>
 <div className="dk-demo-scene dk-demo-ready-scene"><span className="dk-demo-check"><Check size={28}/></span><h3>{t('Your app is ready.','Seu app está pronto.')}</h3><p>{t('Meet Café Aurora. Made from your idea.','Conheça o Café Aurora. Feito a partir da sua ideia.')}</p><div className={`dk-demo-faux-button${clicking&&stage==='ready'?' is-clicked':''}`}>{t('Open app','Abrir aplicativo')}<ArrowUpRight size={16}/><MousePointer2 className={`dk-demo-cursor dk-target-cursor${cursorVisible?' is-visible':''}${clicking?' is-clicking':''}`} size={27} fill="#172034" stroke="white" strokeWidth={1.6}/></div></div>
 <AuroraPreview locale={locale} time={ms} reduced={reduced}/>
 </div>{stage==='cta'&&<div className="dk-demo-invitation"><div className="dk-invitation-art" aria-hidden="true"><i/><i/><i/></div><span className="dk-invitation-eyebrow"><img src="/tools-assets/dk.png" width="20" height="20" alt=""/>{t('YOUR IDEA IS NEXT','A PRÓXIMA IDEIA É SUA')}</span><h3>{t('Your idea.','Sua ideia.')}<br/><em>{t('Your next app.','Seu próximo app.')}</em></h3><p>{t('Turn your idea into an app with DK Create.','Transforme sua ideia em um app com o DK Create.')}</p><Link href="/create">{t('Build your own app','Crie seu próprio app')}<ArrowUpRight size={18}/></Link><small className="dk-invitation-signature">{t('Bring it to life with DK Create','Dê vida à sua ideia com o DK Create')}</small></div>}</div><div className="dk-demo-caption"><span>{t('From idea to app · Demo','Da ideia ao app · Demonstração')}</span><div><Link href="/create">{t('Build yours','Crie o seu')}<ArrowUpRight size={12}/></Link>{!reduced&&<button type="button" aria-label={paused?t('Play animation','Reproduzir animação'):t('Pause animation','Pausar animação')} onClick={()=>setPaused(!paused)}>{paused?<Play size={13}/>:<Pause size={13}/>}</button>}</div></div></div>;
}
