'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Plus,Search,FolderOpen,ArrowUpRight,Shapes,Code2,Clock3,RefreshCw,Monitor,Cloud,Image,FileText,Music2} from 'lucide-react';
import PlatformHeader from './PlatformHeader';
import PlatformFooter from './PlatformFooter';
import WorkspaceModal from './WorkspaceModal';
import ProjectCard from './ProjectCard';
import {findTool,type Locale} from '@/lib/tools/registry';
import './portal.css';
import './reference.css';
import './workspace.css';
type Project={id:string;title:string;kind:'tools'|'create';status:string;updatedAt?:string;href:string;description?:string;tags?:string[]};
export default function Projects({ownerId,createProjects,createError}:{ownerId:string;createProjects:Project[];createError:boolean}){
 const router=useRouter();
 const [reload,setReload]=useState(0);
 const [locale,setLocale]=useState<Locale>('en'),[localProjects,setLocalProjects]=useState<Project[]>([]),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('recent'),[newOpen,setNewOpen]=useState(false);
 const t=(en:string,pt:string)=>locale==='pt'?pt:en;
 useEffect(()=>{try{const lang=localStorage.getItem('dk-language');setLocale(lang==='pt'||lang==='en'?lang:navigator.language.startsWith('pt')?'pt':'en');}catch{}},[]);
 useEffect(()=>{const read=()=>{try{const values:unknown=JSON.parse(localStorage.getItem('dk-tool-projects:'+ownerId)||'[]');if(!Array.isArray(values))throw Error();setLocalProjects(values.flatMap(item=>{if(!item||typeof item.id!=='string'||typeof item.title!=='string'||typeof item.tool!=='string'||!findTool(item.tool))return [];return [{id:item.id,title:item.title,kind:'tools' as const,status:'draft',updatedAt:typeof item.updatedAt==='string'?item.updatedAt:undefined,href:'/tools/'+item.tool+'?draft='+encodeURIComponent(item.id)}];}));setStorageError(false);}catch{setStorageError(true);}setLoaded(true);};read();window.addEventListener('storage',read);window.addEventListener('focus',read);return()=>{window.removeEventListener('storage',read);window.removeEventListener('focus',read);};},[ownerId,reload]);
 const projects=[...localProjects,...createProjects];
 const visible=projects.filter(p=>(filter==='all'||p.kind===filter)&&p.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):(Date.parse(b.updatedAt||'')||0)-(Date.parse(a.updatedAt||'')||0));
 const status=(value:string)=>value==='draft'?t('Draft','Rascunho'):value==='ready'?t('Ready','Pronto'):value==='failed'?t('Needs attention','Precisa de atenção'):value==='cancelled'?t('Stopped','Interrompido'):t('In progress','Em andamento');
 return <div className="dk-portal"><PlatformHeader locale={locale} onLocale={l=>{setLocale(l);try{localStorage.setItem('dk-language',l);}catch{}}}/><main className="dk-projects"><header className="dk-projects-heading"><div><p className="dk-eyebrow">{t('YOUR DEVKILLER WORKSPACE','SEU ESPAÇO DEVKILLER')}</p><h1>{t('My projects','Meus projetos')}</h1><p>{t('Your saved work. Your next big idea. All in one place.','Seus trabalhos salvos. Sua próxima grande ideia. Tudo em um lugar.')}</p></div><button className="dk-project-primary" onClick={()=>setNewOpen(true)}><Plus size={18}/>{t('New project','Novo projeto')}</button></header>
 <section className="dk-project-overview" aria-label={t('Project overview','Visão geral dos projetos')}><div><FolderOpen/><strong>{loaded?projects.length:'—'}</strong><span>{t('Saved projects','Projetos salvos')}</span></div><div><Shapes/><strong>{loaded?localProjects.length:'—'}</strong><span>DK Tools</span></div><div><Code2/><strong>{createError?'—':createProjects.length}</strong><span>DK Create</span></div></section>
 <section className="dk-project-library"><div className="dk-project-controls"><div className="dk-project-tabs" role="group" aria-label={t('Filter projects','Filtrar projetos')}>{['all','tools','create'].map(value=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value==='all'?t('All projects','Todos'):value==='tools'?'DK Tools':'DK Create'}</button>)}</div><div className="dk-project-search"><Search size={17}/><input aria-label={t('Search projects','Buscar projetos')} placeholder={t('Search your projects…','Busque seus projetos…')} value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label={t('Sort projects','Ordenar projetos')} value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">{t('Most recent','Mais recentes')}</option><option value="name">{t('Name A–Z','Nome A–Z')}</option></select></div>
 {(createError||storageError)&&<div className="dk-workspace-notice" role="alert">{createError?t('Create projects could not be loaded. Your saved work has not been deleted.','Não foi possível carregar os projetos Create. Seus trabalhos salvos não foram excluídos.'):t('Browser storage could not be read. Tools drafts may be unavailable.','Não foi possível ler o armazenamento deste navegador. Rascunhos Tools podem estar indisponíveis.')}<button onClick={()=>{setReload(x=>x+1);router.refresh();}}><RefreshCw size={14}/>{t('Try again','Tentar novamente')}</button></div>}
 {!loaded?<div className="dk-project-empty" role="status">{t('Loading your workspace…','Carregando seu espaço…')}</div>:visible.length?<div className="dk-project-grid">{visible.map(project=><ProjectCard key={project.kind+project.id} project={project} locale={locale}/>)}</div>:<div className="dk-project-empty"><div className="dk-project-empty-icon"><FolderOpen size={35}/></div><h2>{query?t('No matches this time.','Nenhum resultado desta vez.'):t('A fresh space for your ideas.','Um novo espaço para suas ideias.')}</h2><p>{query?t('Try another name or choose a different filter.','Tente outro nome ou escolha outro filtro.'):t('Save a draft in DK Tools or start an app in Create. Your projects will appear here, ready to continue.','Salve um rascunho no DK Tools ou comece um app no Create. Seus projetos aparecerão aqui, prontos para continuar.')}</p>{query?<button className="dk-project-primary" onClick={()=>{setQuery('');setFilter('all');}}>{t('Clear filters','Limpar filtros')}</button>:<button className="dk-project-primary" onClick={()=>setNewOpen(true)}><Plus size={17}/>{t('Create your first project','Crie seu primeiro projeto')}</button>}</div>}
 <p className="dk-project-storage"><Monitor size={15}/>{t('Tools drafts stay in this browser, linked to your account; input files are not saved. Create shows your 50 most recent apps stored in your account.','Rascunhos Tools ficam neste navegador, vinculados à sua conta; arquivos de entrada não são salvos. Create mostra seus 50 apps mais recentes armazenados na conta.')}</p></section>
 </main><PlatformFooter locale={locale}/>{newOpen&&<WorkspaceModal title={t('What will you create?','O que você vai criar?')} closeLabel={t('Close','Fechar')} onClose={()=>setNewOpen(false)}><p className="dk-new-project-intro">{t('Choose where to start. Your work stays together in My projects.','Escolha por onde começar. Seus trabalhos ficam reunidos em Meus projetos.')}</p><div className="dk-new-project-options"><Link href="/tools"><Shapes size={26}/><strong>DK Tools</strong><p>{t('Edit files, create assets and save your settings as a draft.','Edite arquivos, crie materiais e salve suas configurações como rascunho.')}</p><span>{t('Explore tools','Explorar ferramentas')}<ArrowUpRight size={16}/></span></Link><Link href="/create"><Code2 size={26}/><strong>DK Create</strong><p>{t('Turn your idea into an app. Start with a prompt and refine it.','Transforme sua ideia em um app. Comece com um prompt e refine o resultado.')}</p><span>{t('Build an app','Criar aplicativo')}<ArrowUpRight size={16}/></span></Link></div><p className="dk-new-project-intro">{t('Or jump straight into a tool','Ou vá direto para uma ferramenta')}</p><div className="dk-project-shortcuts"><Link href="/tools/image/resize"><Image size={17}/>{t('Image','Imagem')}</Link><Link href="/tools/pdf/merge"><FileText size={17}/>PDF</Link><Link href="/tools/audio/trim"><Music2 size={17}/>{t('Audio','Áudio')}</Link><Link href="/tools/svg/editor"><Shapes size={17}/>SVG</Link></div></WorkspaceModal>}</div>;
}
