'use client';
import {useState} from 'react';
import Link from 'next/link';
import {MoreHorizontal,ArrowUpRight,Download,Trash2,Clock3} from 'lucide-react';
import type {Locale} from '@/lib/tools/registry';
import './project-card.css';
export type ProjectCardData={id:string;title:string;kind:'tools'|'create';status:string;updatedAt?:string;href:string;description?:string;tags?:string[]};
export default function ProjectCard({project,locale='en',onOpen,onDelete}:{project:ProjectCardData;locale?:Locale;onOpen?:()=>void;onDelete?:()=>void}){
 const [noImage,setNoImage]=useState(false);const t=(en:string,pt:string)=>locale==='pt'?pt:en;
 const ready=project.status==='ready';const status=ready?t('Ready','Pronto'):project.status==='draft'?t('Draft','Rascunho'):project.status==='failed'?t('Needs attention','Precisa de atenção'):project.status==='cancelled'?t('Stopped','Interrompido'):t('Building','Em criação');
 const stamp=Date.parse(project.updatedAt||'');const delta=Date.now()-stamp;const days=Math.floor(delta/86400000);const relative=Number.isFinite(stamp)?new Intl.RelativeTimeFormat(locale==='pt'?'pt-BR':'en',{numeric:'auto'}).format(-Math.max(0,days||Math.floor(delta/3600000)),days?'day':'hour'):t('Saved draft','Rascunho salvo');
 const open=(e:React.MouseEvent)=>{if(onOpen){e.preventDefault();onOpen();}};
 return <article className={'dk-project-tile '+(project.kind==='create'?'is-app':'is-tool')}><div className="dk-project-shot">{project.kind==='create'&&ready&&!noImage?<img loading="lazy" src={'/api/generator/projects/'+encodeURIComponent(project.id)+'/thumbnail'} alt={t('Preview of ','Prévia de ')+project.title} onError={()=>setNoImage(true)}/>:<div className="dk-project-placeholder"><span>{project.title.split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase()}</span><small>{ready?t('Preview unavailable','Prévia indisponível'):t('Your next idea, taking shape','Sua próxima ideia ganhando forma')}</small></div>}<span className={'dk-project-state '+(ready?'is-ready':'')}><i/>{status}</span></div><div className="dk-project-tile-body"><div className="dk-project-type">{project.kind==='create'?'APP':'TOOL'}<div className="dk-project-actions">{onDelete&&<button type="button" className="dk-project-delete" onClick={onDelete} aria-label={t("Delete ","Apagar ")+project.title} title={t("Delete project","Apagar projeto")}><Trash2 size={16}/></button>}<details className="dk-project-menu"><summary aria-label={t('Actions for ','Ações para ')+project.title}><MoreHorizontal size={19}/></summary><div><Link href={project.href} onClick={open}><ArrowUpRight size={14}/>{t('Open project','Abrir projeto')}</Link>{ready&&project.kind==='create'&&<a href={'/api/generator/workbench?run='+encodeURIComponent(project.id)+'&download=zip'}><Download size={14}/>{t('Export source','Exportar código')}</a>}{onDelete&&<button onClick={onDelete}><Trash2 size={14}/>{t('Delete project','Excluir projeto')}</button>}</div></details></div></div><h2><Link className="dk-project-open" href={project.href} onClick={open}>{project.title}</Link></h2><p>{project.description||(project.kind==='create'?t('Your app, ready for the next step.','Seu app, pronto para o próximo passo.'):t('Your saved settings and content.','Suas configurações e conteúdo salvos.'))}</p><div className="dk-project-tags">{(project.tags||[project.kind==='create'?'React':'DK Tools']).slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><footer title={Number.isFinite(stamp)?new Date(stamp).toLocaleString():undefined}><Clock3 size={12}/>{t('Updated ','Atualizado ')}{relative}</footer></div></article>;
}
