import Link from 'next/link';
import {Grid2X2,ArrowUpRight,ArrowRight,ImageDown,Scaling,Crop,Images,ImageUp,Eraser,FileCode2,SwatchBook,AppWindow,Files,Scissors,ListOrdered,FileImage,FileDown,RotateCw,FileOutput,LockKeyhole,LockKeyholeOpen,AudioLines,FileAudio,SlidersHorizontal,Volume2,Waves,VolumeX,Braces,Minimize2,Binary,Link2,Fingerprint,Hash,KeyRound,Regex,Diff,CaseSensitive,Blend,Pipette,Contrast,Layers,Square,QrCode,PenTool,Shapes,Repeat2,LoaderCircle,ScanLine,CodeXml,Eye,type LucideIcon} from 'lucide-react';
import {categories,label,tools,type Locale,type Category,type Tool} from '@/lib/tools/registry';
const glyphs:Record<Category,Record<string,LucideIcon>>={
 image:{compress:ImageDown,resize:Scaling,crop:Crop,convert:Images,heic:ImageUp,background:Eraser,base64:FileCode2,palette:SwatchBook,favicon:AppWindow},
 pdf:{merge:Files,split:Scissors,reorder:ListOrdered,'images-to-pdf':FileImage,'to-images':Images,compress:FileDown,rotate:RotateCw,extract:FileOutput,protect:LockKeyhole,unlock:LockKeyholeOpen},
 audio:{trim:Scissors,convert:FileAudio,bitrate:SlidersHorizontal,volume:Volume2,fade:Waves,silence:VolumeX},
 text:{json:Braces,minify:Minimize2,base64:Binary,url:Link2,uuid:Fingerprint,hash:Hash,jwt:KeyRound,regex:Regex,diff:Diff,count:CaseSensitive},
 design:{gradient:Blend,color:Pipette,contrast:Contrast,shadow:Layers,radius:Square,qr:QrCode},
 svg:{editor:PenTool,blob:Shapes,wave:Waves,pattern:Repeat2,gradient:Blend,spinner:LoaderCircle,'to-png':ImageDown,trace:ScanLine,minify:Minimize2,viewer:Eye,code:CodeXml}
};
// Editorial starting selection; no usage analytics or fabricated popularity ranks.
const featured:Record<Category,string[]>={image:['compress','resize','convert','crop'],pdf:['merge','split','compress','images-to-pdf'],audio:['trim','convert','volume'],text:['json','base64','diff','count'],design:['qr','gradient','color','contrast'],svg:['editor','wave','to-png','minify']};
const subtitles:Record<Category,[string,string]>={image:['Less weight. More possibilities.','Menos peso. Mais possibilidades.'],pdf:['Your documents, in order.','Seus documentos, em ordem.'],audio:['Find the sound you need.','Encontre o som que você precisa.'],text:['Make every character count.','Dê sentido a cada caractere.'],design:['The details that make it yours.','Os detalhes que deixam sua marca.'],svg:['Small vectors. Endless possibilities.','Pequenos vetores. Muitas possibilidades.']};
const categoryIcons:Record<Category,LucideIcon>={image:Images,pdf:FileDown,audio:AudioLines,text:CodeXml,design:Pipette,svg:PenTool};
export function CategoryTiles({locale}:{locale:Locale}){return <section className="dk-category-overview"><div className="dk-category-overview-heading"><Grid2X2 size={23}/><div><h2>{locale==='pt'?'Categorias':'Categories'}</h2><p>{locale==='pt'?'Encontre a ferramenta certa para sua tarefa.':'Find the right tool for your task.'}</p></div></div><div className="dk-category-tiles">{(Object.keys(categories) as Category[]).map(category=>{const Icon=categoryIcons[category];return <Link href={`/tools/${category}`} key={category} className={`dk-category-tile dk-tile-${category}`}><span className="dk-category-tile-icon"><Icon size={26} strokeWidth={1.8}/></span><strong>{label(categories[category],locale)}</strong><div><span>{tools.filter(t=>t.category===category).length} {locale==='pt'?'ferramentas':'tools'}</span><ArrowRight size={19}/></div></Link>;})}</div></section>;}
export default function ToolCatalog({locale,selected,query}:{locale:Locale;selected:Category|'';query:string}){
 const t=(a:string,b:string)=>locale==='pt'?b:a;const searching=!!query.trim();
 const groups=(Object.keys(categories) as Category[]).filter(c=>!selected||c===selected).map(category=>{const all=tools.filter(tool=>tool.category===category&&`${tool.name.join(' ')} ${tool.description.join(' ')}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));return {category,total:tools.filter(tool=>tool.category===category).length,items:!selected&&!searching?featured[category].map(action=>all.find(x=>x.action===action)).filter((x):x is Tool=>!!x):all};}).filter(g=>g.items.length);
 return <div className="dk-catalog">{groups.map(({category,items,total})=><section className={`dk-category dk-category-${category}`} key={category} aria-labelledby={`dk-category-${category}`}><div className="dk-category-heading"><div><div className="dk-category-label"><span className="dk-category-dot"/><h2 id={`dk-category-${category}`}>{label(categories[category],locale)}</h2><span className="dk-category-count">{total}</span></div><p>{label(subtitles[category],locale)}</p></div>{!selected&&<Link className="dk-view-all" href={`/tools/${category}`}>{t('View all','Ver todas')}<ArrowRight size={15}/></Link>}</div><div className="dk-grid dk-category-grid">{items.map(item=>{const Icon=glyphs[category][item.action]||AudioLines;return <Link className="dk-tool dk-refined-tool" href={`/tools/${item.id}`} key={item.id}><div className="dk-tool-heading"><span className="dk-tool-glyph"><Icon size={25} strokeWidth={1.55}/></span><ArrowUpRight className="dk-tool-arrow" size={17} strokeWidth={1.5}/></div><h3>{label(item.name,locale)}</h3><p>{label(item.description,locale)}</p></Link>;})}</div></section>)}{!groups.length&&<p className="dk-empty" role="status">{t('No tools match your search.','Nenhuma ferramenta encontrada.')}</p>}</div>;
}
