import {number,type Output} from './core';import type {Values} from './options';
export function wavBlob(channels:Float32Array[],rate:number){const frames=channels[0].length,count=channels.length;const bytes=new ArrayBuffer(44+frames*count*2);const view=new DataView(bytes);const str=(at:number,s:string)=>{for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i));};str(0,'RIFF');view.setUint32(4,bytes.byteLength-8,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,count,true);view.setUint32(24,rate,true);view.setUint32(28,rate*count*2,true);view.setUint16(32,count*2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,bytes.byteLength-44,true);let at=44;for(let i=0;i<frames;i++)for(let ch=0;ch<count;ch++){const x=Math.max(-1,Math.min(1,channels[ch][i]));view.setInt16(at,x<0?x*32768:x*32767,true);at+=2;}return new Blob([bytes],{type:'audio/wav'});}
export async function audioEngine(action:string,file:File,v:Values,signal:AbortSignal,progress:(s:string)=>void):Promise<Output[]>{
 const context=new AudioContext();let audio:AudioBuffer;try{audio=await context.decodeAudioData(await file.arrayBuffer());}finally{await context.close();}if(audio.duration>600||audio.numberOfChannels>2)throw Error('Use up to 10 minutes of mono/stereo audio. / Use até 10 minutos de áudio mono/estéreo.');if(signal.aborted)throw new DOMException('Cancelled','AbortError');
 let start=action==='trim'?number(v.start,0,0,audio.duration):0,end=action==='trim'?number(v.end,audio.duration,0,audio.duration):audio.duration;if(end<=start)throw Error('End must be after start. / O fim deve ser após o início.');let first=Math.floor(start*audio.sampleRate),last=Math.min(audio.length,Math.floor(end*audio.sampleRate));const channels=Array.from({length:audio.numberOfChannels},(_,i)=>audio.getChannelData(i));
 if(action==='silence'){const threshold=10**(number(v.threshold,-40,-90,-1)/20);while(first<last&&channels.every(c=>Math.abs(c[first])<=threshold))first++;while(last>first&&channels.every(c=>Math.abs(c[last-1])<=threshold))last--;if(first===last)throw Error('The entire file is below the selected threshold. / Todo o arquivo está abaixo do limiar.');}
 const out=channels.map(c=>c.slice(first,last));const gain=action==='volume'?number(v.volume,1,0,4):1;const fade=action==='fade'?number(v.fade,1,0,(last-first)/audio.sampleRate/2)*audio.sampleRate:0;out.forEach(c=>{for(let i=0;i<c.length;i++)c[i]*=gain*(fade?Math.min(1,i/fade,(c.length-1-i)/fade):1);});const wav=wavBlob(out,audio.sampleRate);if(v.format==='wav')return [{name:'audio.wav',blob:wav,preview:'audio'}];
 progress('Loading audio encoder… / Carregando codificador de áudio…');const {FFmpeg}=await import('@ffmpeg/ffmpeg');const ffmpeg=new FFmpeg();let wasmUrl='';const abort=()=>ffmpeg.terminate();signal.addEventListener('abort',abort,{once:true});try{if(signal.aborted)throw new DOMException('Cancelled','AbortError');const chunks=await Promise.all([0,1,2].map(async i=>{const response=await fetch('/tools-assets/ffmpeg/ffmpeg-core.wasm.'+i,{signal});if(!response.ok)throw Error('Audio engine download failed. / Falha ao baixar o motor de áudio.');return response.arrayBuffer();}));wasmUrl=URL.createObjectURL(new Blob(chunks,{type:'application/wasm'}));await ffmpeg.load({classWorkerURL:'/tools-assets/ffmpeg/worker.js',coreURL:'/tools-assets/ffmpeg/ffmpeg-core.js',wasmURL:wasmUrl});await ffmpeg.writeFile('input.wav',new Uint8Array(await wav.arrayBuffer()));const format=v.format==='ogg'?'ogg':'mp3';const code=await ffmpeg.exec(['-i','input.wav','-c:a',format==='ogg'?'libvorbis':'libmp3lame','-b:a',`${number(v.bitrate,192,32,320)}k`,`output.${format}`],60000);if(code!==0)throw Error('Audio encoding failed. / Falha ao codificar áudio.');const data=await ffmpeg.readFile(`output.${format}`);if(typeof data==='string')throw Error('Invalid audio output');return [{name:`audio.${format}`,blob:new Blob([new Uint8Array(data).buffer],{type:format==='ogg'?'audio/ogg':'audio/mpeg'}),preview:'audio'}];}finally{signal.removeEventListener('abort',abort);ffmpeg.terminate();if(wasmUrl)URL.revokeObjectURL(wasmUrl);}
}
