export type Output={name:string;blob:Blob;text?:string;preview?:'image'|'audio'|'video';note?:string;optimization?:{before:number;after:number;saved:number}};
export function textOutput(text:string,name='result.txt',type='text/plain'):Output{return {name,blob:new Blob([text],{type}),text};}
export function bytesBlob(bytes:Uint8Array,type:string){return new Blob([new Uint8Array(bytes).buffer],{type});}
export function number(value:string|undefined,fallback:number,min:number,max:number){const n=value===undefined||value===''?fallback:Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`Use a value between ${min} and ${max}. / Use um valor entre ${min} e ${max}.`);return n;}
export function pageNumbers(value:string,total:number){if(!value.trim())return Array.from({length:total},(_,i)=>i);const pages:number[]=[];for(const piece of value.split(',')){const m=piece.trim().match(/^(\d+)(?:-(\d+))?$/);if(!m)throw Error('Invalid page selection. / Seleção de páginas inválida.');const start=Number(m[1]),end=Number(m[2]||m[1]);if(start<1||end>total||start>end)throw Error('Page range is outside this document. / Intervalo fora do documento.');for(let p=start;p<=end;p++)pages.push(p-1);if(pages.length>1000)throw Error('Select up to 1000 pages. / Selecione até 1000 páginas.');}return pages;}
export function hexRgb(hex:string){if(!/^#[0-9a-f]{6}$/i.test(hex))throw Error('Invalid HEX color. / Cor HEX inválida.');return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
export function contrast(a:string,b:string){const lum=(h:string)=>hexRgb(h).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
export function escapeXml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));}
export async function canvasBlob(canvas:HTMLCanvasElement,type='image/png',quality=.8){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image encoding failed. / Falha ao codificar imagem.')),type,quality));}
export function canvas2d(w:number,h:number){if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w*h>24000000)throw Error('Use dimensions within 24 megapixels. / Use dimensões até 24 megapixels.');const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)throw Error('Canvas unavailable. / Canvas indisponível.');return {c,ctx};}
