import {bytesBlob,canvas2d,canvasBlob,hexRgb,number,textOutput,type Output} from './core';import type {Values} from './options';
export async function imageEngine(action:string,file:File,v:Values):Promise<Output[]>{
 if(action==='base64'){const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('File could not be read'));r.readAsDataURL(file);});return [textOutput(data,'image-base64.txt')];}
 let input:Blob=file;if(action==='heic'){const {heicTo}=await import('heic-to/csp');input=await heicTo({blob:file,type:'image/png',quality:1});}
 const bitmap=await createImageBitmap(input);try{
 const width=action==='resize'||action==='crop'?Math.round(number(v.width,bitmap.width,1,12000)):bitmap.width;const height=action==='resize'||action==='crop'?Math.round(number(v.height,bitmap.height,1,12000)):bitmap.height;
 const {c,ctx}=canvas2d(width,height);const format=action==='background'?'png':action==='compress'?(v.format==='jpeg'?'jpeg':'webp'):v.format||'png';if(format==='jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);}
 if(action==='crop'){const x=number(v.x,0,0,bitmap.width-1),y=number(v.y,0,0,bitmap.height-1);if(x+width>bitmap.width||y+height>bitmap.height)throw Error('Crop exceeds image boundaries. / Recorte excede a imagem.');ctx.drawImage(bitmap,x,y,width,height,0,0,width,height);}else ctx.drawImage(bitmap,0,0,width,height);
 if(action==='background'){const target=hexRgb(v.color||'#ffffff'),tolerance=number(v.tolerance,35,0,255),pixels=ctx.getImageData(0,0,width,height);for(let i=0;i<pixels.data.length;i+=4){const distance=Math.max(...target.map((val,k)=>Math.abs(val-pixels.data[i+k])));if(distance<=tolerance)pixels.data[i+3]=0;}ctx.putImageData(pixels,0,0);}
 if(action==='palette'){const sample=canvas2d(100,100);sample.ctx.drawImage(bitmap,0,0,100,100);const data=sample.ctx.getImageData(0,0,100,100).data;const counts=new Map<string,number>();for(let i=0;i<data.length;i+=4){if(data[i+3]<128)continue;const key='#'+[data[i],data[i+1],data[i+2]].map(x=>Math.min(255,Math.round(x/24)*24).toString(16).padStart(2,'0')).join('');counts.set(key,(counts.get(key)||0)+1);}return [textOutput(JSON.stringify([...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([hex])=>hex),null,2),'palette.json')];}
 if(action==='favicon'){const outputs:Output[]=[];const icoParts:Uint8Array[]=[];for(const size of [16,32,48,180,192,512]){const out=canvas2d(size,size);const scale=Math.min(size/bitmap.width,size/bitmap.height);out.ctx.drawImage(bitmap,(size-bitmap.width*scale)/2,(size-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);const blob=await canvasBlob(out.c);outputs.push({name:`favicon-${size}.png`,blob,preview:'image'});if(size<=48)icoParts.push(new Uint8Array(await blob.arrayBuffer()));}const header=new Uint8Array(6+16*3);const dv=new DataView(header.buffer);dv.setUint16(2,1,true);dv.setUint16(4,3,true);let offset=header.length;icoParts.forEach((b,i)=>{const at=6+16*i;header[at]=[16,32,48][i];header[at+1]=header[at];dv.setUint16(at+4,1,true);dv.setUint16(at+6,32,true);dv.setUint32(at+8,b.length,true);dv.setUint32(at+12,offset,true);offset+=b.length;});outputs.push({name:'favicon.ico',blob:new Blob([header,...icoParts.map(b=>b.buffer as ArrayBuffer)],{type:'image/x-icon'})});return outputs;}
 let blob=await canvasBlob(c,`image/${format}`,number(v.quality,80,1,100)/100);if(blob.type!=='image/'+format)throw Error('Unsupported output format. / Formato não suportado.');if(action==='compress'){const saved=Math.max(0,file.size-blob.size);if(!saved)blob=file;return [{name:saved?'compressed.'+(format==='jpeg'?'jpg':format):file.name,blob,preview:'image',optimization:{before:file.size,after:blob.size,saved}}];}return [{name:`image.${blob.type.split('/')[1]}`,blob,preview:'image',note:`${file.size} → ${blob.size} bytes`}];
 }finally{bitmap.close();}
}
