import type {Tool} from './registry';
export type Values=Record<string,string>;
export type Field={key:string;en:string;pt:string;value:string;type?:'number'|'color'|'password';choices?:string[]};
const field=(key:string,en:string,pt:string,value:string,type?:Field['type'],choices?:string[]):Field=>({key,en,pt,value,type,choices});
export function fieldsFor(t:Tool):Field[]{const a=t.action,c=t.category;
 if(a==='video')return [field('format','Export as','Exportar como','mp4',undefined,['mp4','webm','gif','mp3','wav']),field('start','Start (seconds)','Início (segundos)','0','number'),field('duration','Duration (seconds, max 600)','Duração (segundos, máximo 600)','60','number'),field('size','Frame','Enquadramento','original',undefined,['original','vertical','square']),field('mute','Remove audio','Remover áudio','no',undefined,['no','yes'])];
 if(a==='ocr')return [field('language','Document language','Idioma do documento','eng',undefined,['eng','por'])];
 const color=field('color','Color','Cor','#ff4b72','color'),color2=field('color2','Second color','Segunda cor','#ffad75','color');
 const quality=field('quality','Quality (1–100)','Qualidade (1–100)','80','number');
 const width=field('width','Width (px)','Largura (px)','800','number'),height=field('height','Height (px)','Altura (px)','600','number');
 const format=field('format','Output format','Formato de saída','webp',undefined,['webp','png','jpeg']);
 if(c==='image'){if(a==='compress')return [field('format','Compressed format','Formato comprimido','webp',undefined,['webp','jpeg']),quality];if(a==='palette')return [];if(a==='base64'||a==='favicon')return [];if(a==='background')return [field('mode','Cutout method','Método de recorte','automatic',undefined,['automatic','solid']),field('color','Background color','Cor do fundo','#ffffff','color'),field('tolerance','Color tolerance (0–255)','Tolerância de cor (0–255)','35','number')];if(a==='crop')return [field('x','Left (px)','Esquerda (px)','0','number'),field('y','Top (px)','Topo (px)','0','number'),width,height,format];return [...(a==='resize'?[width,height]:[]),format,quality];}
 if(c==='pdf'){if(['extract','reorder','rotate','to-images'].includes(a))return [field('pages','Pages (empty = all; e.g. 1,3-5)','Páginas (vazio = todas; ex. 1,3-5)',''),...(a==='rotate'?[field('angle','Rotation','Rotação','90',undefined,['90','180','270'])]:[]),...(a==='to-images'?[field('scale','Render scale','Escala','1.5','number')]:[])];if(['protect','unlock'].includes(a))return [field('password',a==='protect'?'New password':'Known password',a==='protect'?'Nova senha':'Senha conhecida','','password')];return [];}
 if(c==='audio')return [field('format','Output format','Formato de saída','mp3',undefined,a==='bitrate'?['mp3','ogg']:['mp3','wav','ogg']),field('bitrate','Bitrate (kbps)','Bitrate (kbps)','192',undefined,['64','128','192','256','320']),...(a==='trim'?[field('start','Start (seconds)','Início (segundos)','0','number'),field('end','End (seconds, empty = full length)','Fim (segundos, vazio = até o final)','','number')]:[]),...(a==='volume'?[field('volume','Volume multiplier','Multiplicador de volume','1','number')]:[]),...(a==='fade'?[field('fade','Fade in / out (seconds)','Fade in / out (segundos)','1','number')]:[]),...(a==='silence'?[field('threshold','Silence threshold (dB)','Limiar de silêncio (dB)','-40','number')]:[])];
 if(c==='text'){if(['base64','url'].includes(a))return [field('mode','Operation','Operação','encode',undefined,['encode','decode'])];if(a==='uuid')return [field('count','How many','Quantidade','1','number')];if(a==='hash')return [field('algorithm','Algorithm','Algoritmo','SHA-256',undefined,['SHA-256','SHA-384','SHA-512'])];if(a==='regex')return [field('pattern','Pattern','Expressão','\\w+'),field('flags','Flags','Flags','g')];return [];}
 if(c==='design'){if(a==='qr')return [field('content','Text or URL','Texto ou URL','https://example.com'),field('size','Size (px)','Tamanho (px)','512','number')];if(a==='color')return [color];if(a==='contrast')return [field('color','Text color','Cor do texto','#111522','color'),field('color2','Background color','Cor de fundo','#ffffff','color')];if(a==='gradient')return [color,color2,field('angle','Angle','Ângulo','120','number')];if(a==='radius')return ['tl','tr','br','bl'].map((k,i)=>field(k,['Top left','Top right','Bottom right','Bottom left'][i],['Superior esquerdo','Superior direito','Inferior direito','Inferior esquerdo'][i],'24','number'));return [color,field('x','Offset X','Deslocamento X','0','number'),field('y','Offset Y','Deslocamento Y','12','number'),field('blur','Blur','Desfoque','30','number'),field('spread','Spread','Expansão','0','number')];}
 if(c==='svg'){if(a==='to-png')return [width,height];if(['viewer','minify','code','editor'].includes(a))return [];if(a==='trace')return [field('colors','Number of colors','Quantidade de cores','8','number')];return [color,color2,width,height,field('seed','Variation','Variação','1','number')];}return [];
}
