import {PDFDocument,degrees} from 'pdf-lib';import {bytesBlob,canvas2d,canvasBlob,number,pageNumbers,type Output} from './core';import type {Values} from './options';
export async function pdfEngine(action:string,files:File[],v:Values,signal:AbortSignal):Promise<Output[]>{
 if(['compress','protect','unlock'].includes(action)){if(['protect','unlock'].includes(action)&&!v.password)throw Error('Enter a password. / Informe uma senha.');if(v.password?.length>127)throw Error('Password limit: 127 characters. / Limite: 127 caracteres.');const data=await files[0].arrayBuffer();const bytes=await new Promise<Uint8Array>((resolve,reject)=>{const worker=new Worker('/tools-assets/qpdf-worker.js');const stop=()=>{clearTimeout(timer);worker.terminate();signal.removeEventListener('abort',abort);};const abort=()=>{stop();reject(new DOMException('Cancelled','AbortError'));};const timer=setTimeout(()=>{stop();reject(Error('PDF processing timed out. / Tempo de PDF excedido.'));},60000);worker.onmessage=e=>{stop();e.data.error?reject(Error(e.data.error)):resolve(e.data.bytes);};worker.onerror=()=>{stop();reject(Error('PDF engine failed. / Falha no motor PDF.'));};signal.addEventListener('abort',abort,{once:true});if(signal.aborted)return abort();worker.postMessage({action,password:v.password,data},[data]);});if(action==='compress'){const saved=Math.max(0,files[0].size-bytes.length);return [{name:saved?'compressed.pdf':files[0].name,blob:saved?bytesBlob(bytes,'application/pdf'):files[0],optimization:{before:files[0].size,after:Math.min(files[0].size,bytes.length),saved}}];}return [{name:`${action}.pdf`,blob:bytesBlob(bytes,'application/pdf'),note:`${files[0].size} → ${bytes.length} bytes`}];}
 const result=await PDFDocument.create();
 if(action==='images-to-pdf'){for(const file of files){if(signal.aborted)throw new DOMException('Cancelled','AbortError');const bitmap=await createImageBitmap(file);try{const {c,ctx}=canvas2d(bitmap.width,bitmap.height);ctx.drawImage(bitmap,0,0);const image=await result.embedPng(await (await canvasBlob(c)).arrayBuffer());const scale=Math.min(1,1440/image.width,1440/image.height);const page=result.addPage([image.width*scale,image.height*scale]);page.drawImage(image,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});}finally{bitmap.close();}}return [{name:'images.pdf',blob:bytesBlob(await result.save(),'application/pdf')}];}
 if(action==='to-images'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/tools-assets/pdf.worker.min.mjs';const task=pdfjs.getDocument({data:await files[0].arrayBuffer()});const abort=()=>{void task.destroy();};signal.addEventListener('abort',abort,{once:true});try{const pdf=await task.promise;const pages=pageNumbers(v.pages||'',pdf.numPages);if(pages.length>100)throw Error('Export up to 100 pages at a time. / Exporte até 100 páginas por vez.');const outputs:Output[]=[];for(const index of pages){if(signal.aborted)throw new DOMException('Cancelled','AbortError');const page=await pdf.getPage(index+1);const viewport=page.getViewport({scale:number(v.scale,1.5,.2,4)});const {c,ctx}=canvas2d(Math.ceil(viewport.width),Math.ceil(viewport.height));await page.render({canvas:c,canvasContext:ctx,viewport}).promise;outputs.push({name:`page-${index+1}.png`,blob:await canvasBlob(c),preview:'image'});page.cleanup();}return outputs;}finally{signal.removeEventListener('abort',abort);await task.destroy();}}
 for(const file of files){if(signal.aborted)throw new DOMException('Cancelled','AbortError');const input=await PDFDocument.load(await file.arrayBuffer());if(input.getPageCount()>1000)throw Error('PDF limit: 1000 pages. / Limite: 1000 páginas.');const indices=pageNumbers(['reorder','extract','rotate'].includes(action)?v.pages||'':'',input.getPageCount());if(action==='split'){const outputs:Output[]=[];for(const index of indices){const part=await PDFDocument.create();const [page]=await part.copyPages(input,[index]);part.addPage(page);outputs.push({name:`page-${index+1}.pdf`,blob:bytesBlob(await part.save(),'application/pdf')});}return outputs;}
 if(action==='rotate'){for(const i of indices){const p=input.getPage(i);p.setRotation(degrees((p.getRotation().angle+number(v.angle,90,0,360))%360));}return [{name:'rotated.pdf',blob:bytesBlob(await input.save(),'application/pdf')}];}
 const pages=await result.copyPages(input,indices);pages.forEach(p=>result.addPage(p));}
 return [{name:`${action}.pdf`,blob:bytesBlob(await result.save(),'application/pdf')}];
}
