export type Locale = 'en' | 'pt';
export type Category = 'image' | 'pdf' | 'audio' | 'text' | 'design' | 'svg';
export type Tool = {id:string;category:Category;action:string;name:[string,string];description:[string,string];input:'files'|'text'|'design'|'editor';accept?:string;multiple?:boolean};
export const categories:Record<Category,[string,string]>={image:['Images','Imagens'],pdf:['PDF','PDF'],audio:['Audio','Áudio'],text:['Text & Dev','Texto & Dev'],design:['Design','Design'],svg:['SVG','SVG']};
const rows:Record<Category,Array<[string,string,string,string,string]>>={
 image:[['compress','Compress image','Comprimir imagem','Reduce JPG/WebP file size.','Reduza o tamanho de JPG/WebP.'],['resize','Resize image','Redimensionar imagem','Choose exact output dimensions.','Escolha as dimensões de saída.'],['crop','Crop image','Recortar imagem','Crop a rectangular area by coordinates.','Recorte uma área por coordenadas.'],['convert','Convert image','Converter imagem','Convert JPG, PNG and WebP.','Converta JPG, PNG e WebP.'],['heic','HEIC converter','Conversor HEIC','Convert HEIC/HEIF to a web image.','Converta HEIC/HEIF para imagem web.'],['background','Remove background','Remover fundo','Automatically separate the subject and export transparent PNG.','Separe o objeto automaticamente e exporte PNG transparente.'],['base64','Image to Base64','Imagem para Base64','Create a data URL from an image.','Crie uma URL de dados da imagem.'],['palette','Extract palette','Extrair paleta','Find dominant image colors.','Encontre as cores predominantes.'],['favicon','Favicon generator','Gerador de favicon','Download PNG sizes and a multi-size ICO.','Baixe PNGs e um ICO com vários tamanhos.']],
 pdf:[['merge','Merge PDFs','Juntar PDFs','Combine files in the order shown.','Junte arquivos na ordem exibida.'],['split','Split PDF','Dividir PDF','Download each page as a separate PDF.','Baixe cada página em um PDF.'],['reorder','Reorder PDF','Reordenar PDF','Set the page order, such as 3,1,2.','Defina a ordem, como 3,1,2.'],['images-to-pdf','Images to PDF','Imagens para PDF','Combine images into one PDF.','Reúna imagens em um PDF.'],['to-images','PDF to images','PDF para imagens','Render pages to PNG images.','Converta páginas em PNG.'],['compress','Compress PDF','Comprimir PDF','Optimize PDF streams without rasterizing pages. Savings vary.','Otimize sem rasterizar páginas. A redução varia.'],['rotate','Rotate PDF','Girar PDF','Rotate selected pages.','Gire as páginas selecionadas.'],['extract','Extract PDF pages','Extrair páginas','Keep selected pages or page ranges.','Extraia páginas ou intervalos.'],['protect','Protect PDF','Proteger PDF','Encrypt with a password using AES-256.','Proteja com senha e AES-256.'],['unlock','Unlock PDF','Desproteger PDF','Remove encryption using your known password.','Remova proteção com sua senha conhecida.']],
 audio:[['trim','Trim audio','Cortar áudio','Choose start and end times.','Escolha o início e o fim.'],['convert','Convert audio','Converter áudio','Export MP3, WAV or OGG.','Exporte MP3, WAV ou OGG.'],['bitrate','Change bitrate','Alterar bitrate','Choose the bitrate for MP3 or OGG.','Escolha o bitrate de MP3 ou OGG.'],['volume','Adjust volume','Ajustar volume','Increase or reduce audio volume.','Aumente ou reduza o volume.'],['fade','Audio fades','Fades de áudio','Add fade in and fade out.','Adicione fade in e fade out.'],['silence','Trim edge silence','Cortar silêncio nas bordas','Remove leading and trailing silence with an adjustable threshold.','Remova silêncio inicial e final com limiar ajustável.']],
 text:[['json','JSON formatter','Formatador JSON','Validate and format JSON.','Valide e formate JSON.'],['minify','JSON minifier','Minificador JSON','Remove unnecessary JSON whitespace.','Remova espaços desnecessários do JSON.'],['base64','Base64 encode/decode','Base64 codificar/decodificar','Encode or decode Unicode text.','Codifique ou decodifique texto Unicode.'],['url','URL encode/decode','URL codificar/decodificar','Encode or decode URL components.','Codifique ou decodifique componentes URL.'],['uuid','UUID generator','Gerador UUID','Generate cryptographically random UUIDs.','Gere UUIDs aleatórios criptograficamente.'],['hash','Hash generator','Gerador de hash','Calculate SHA-256, SHA-384 or SHA-512.','Calcule SHA-256, SHA-384 ou SHA-512.'],['jwt','JWT viewer','Visualizador JWT','Decode claims. This does not verify a signature.','Leia dados. Isto não verifica assinatura.'],['regex','Regex tester','Testador regex','Test patterns with a time limit.','Teste expressões com limite de tempo.'],['diff','Text diff','Comparar textos','Compare two texts line by line.','Compare dois textos linha a linha.'],['count','Word & character count','Contador de texto','Count words, characters and lines.','Conte palavras, caracteres e linhas.']],
 design:[['gradient','Gradient generator','Gerador de gradiente','Create and export a CSS gradient.','Crie e exporte um gradiente CSS.'],['color','Color picker','Seletor de cores','Convert HEX to RGB and HSL.','Converta HEX para RGB e HSL.'],['contrast','Contrast checker','Verificador de contraste','Compare text and background contrast.','Compare contraste de texto e fundo.'],['shadow','Shadow generator','Gerador de sombra','Adjust and export a CSS box shadow.','Ajuste e exporte uma sombra CSS.'],['radius','Border radius generator','Gerador border-radius','Adjust and export rounded corners.','Ajuste e exporte cantos arredondados.'],['qr','QR code generator','Gerador QR code','Create a static QR code with no redirect service.','Crie QR estático sem redirecionador.']],
 svg:[['editor','SVG Studio','SVG Studio','Create and edit shapes, text and code.','Crie e edite formas, texto e código.'],['blob','Blob generator','Gerador blob','Create an organic vector shape.','Crie uma forma vetorial orgânica.'],['wave','Wave generator','Gerador de ondas','Build a scalable wave divider.','Crie um divisor de ondas.'],['pattern','Pattern generator','Gerador de padrões','Create a repeating geometric pattern.','Crie um padrão geométrico repetido.'],['gradient','SVG gradient','Gradiente SVG','Export a vector gradient background.','Exporte um fundo vetorial em gradiente.'],['spinner','Spinner generator','Gerador de spinner','Create an animated SVG loading indicator.','Crie indicador SVG animado.'],['to-png','SVG to PNG','SVG para PNG','Render sanitized SVG to a PNG.','Converta SVG sanitizado em PNG.'],['trace','PNG to SVG','PNG para SVG','Approximate vector tracing; photos may lose detail.','Vetorização aproximada; fotos podem perder detalhes.'],['minify','SVG minifier','Minificador SVG','Optimize sanitized SVG markup.','Otimize código SVG sanitizado.'],['viewer','SVG viewer','Visualizador SVG','Preview and download sanitized SVG.','Veja e baixe SVG sanitizado.'],['code','SVG code editor','Editor de código SVG','Edit SVG code with a safe preview.','Edite código SVG com prévia segura.']]
};
const allTools:Tool[]=Object.entries(rows).flatMap(([category,items])=>items.map(([action,en,pt,de,dp])=>({id:`${category}/${action}`,category:category as Category,action,name:[en,pt] as [string,string],description:[de,dp] as [string,string],input:(category==='svg'&&action==='editor'?'editor':category==='image'||category==='pdf'||category==='audio'||action==='trace'?'files':category==='text'||['minify','viewer','code','to-png'].includes(action)?'text':'design') as Tool['input'],accept:category==='pdf'&&action!=='images-to-pdf'?'.pdf':category==='audio'?'audio/*':category==='image'&&action==='heic'?'.heic,.heif': 'image/*',multiple:category==='pdf'&&['merge','images-to-pdf'].includes(action)})));
// Curated utility set. Retired routes remain discoverable only for migration.
export const retiredToolIds = new Set(['image/base64','image/palette','audio/bitrate','audio/fade','audio/silence','text/minify','text/url','text/jwt','design/shadow','design/radius','svg/blob','svg/gradient','svg/spinner','svg/viewer','svg/code']);
export const tools:Tool[] = [...allTools.filter(tool=>!retiredToolIds.has(tool.id)),
{id:'audio/video',category:'audio',action:'video',name:['Convert Video','Converter vídeo'],description:['Convert and trim MP4, WebM, GIF or extract audio. 50 MB maximum.','Converta e corte MP4, WebM, GIF ou extraia áudio. Máximo 50 MB.'],input:'files',accept:'video/*'},
{id:'audio/social',category:'audio',action:'video',name:['Social Video Importer','Importar vídeo social'],description:['Upload a video you own or have permission to use. Fit it for social. URL imports are not supported.','Envie um vídeo seu ou autorizado e prepare para redes. Importação por URL não disponível.'],input:'files',accept:'video/*'},
{id:'image/ocr',category:'image',action:'ocr',name:['OCR / Extract Text','OCR / Extrair texto'],description:['Read English or Portuguese text from images and PDFs. Up to 20 pages.','Leia texto em inglês ou português de imagens e PDFs. Até 20 páginas.'],input:'files',accept:'image/png,image/jpeg,image/webp,.pdf'}];
export const retiredTools = allTools.filter(tool=>retiredToolIds.has(tool.id));
export function findTool(id:string){return tools.find(tool=>tool.id===id);}
export function label(value:[string,string],locale:Locale){return value[locale==='pt'?1:0];}
