import DOMPurify from 'dompurify';import {canvas2d,canvasBlob,escapeXml,number,textOutput,type Output} from './core';import type {Values} from './options';
export function safeSvg(source:string){if(source.length>1000000)throw Error('SVG limit: 1 MB. / Limite SVG: 1 MB.');const doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('Enter valid SVG. / Informe um SVG válido.');const cleaned=DOMPurify.sanitize(source,{USE_PROFILES:{svg:true,svgFilters:true},FORBID_TAGS:['foreignObject','script','style','image','a','animate','animateMotion','animateTransform','set'],FORBID_ATTR:['style'],ALLOW_DATA_ATTR:false});const clean=new DOMParser().parseFromString(cleaned,'image/svg+xml');clean.querySelectorAll('*').forEach(el=>{for(const attr of Array.from(el.attributes)){if((['href','xlink:href'].includes(attr.name)&&!attr.value.startsWith('#'))||(/url\s*\(/i.test(attr.value)&&!/^url\(#[\w-]+\)$/.test(attr.value)))el.removeAttribute(attr.name);}});return new XMLSerializer().serializeToString(clean.documentElement);}
export function generatedSvg(action:string,v:Values){const w=number(v.width,800,1,4096),h=number(v.height,600,1,4096),a=escapeXml(v.color||'#ff4b72'),b=escapeXml(v.color2||'#ffad75'),seed=number(v.seed,1,0,1000);let content='';const defs=`<defs><linearGradient id="g"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs>`;
 if(action==='gradient')content=`${defs}<rect width="${w}" height="${h}" fill="url(#g)"/>`;
 if(action==='wave')content=`${defs}<path d="M0 ${h*.5} Q${w*.25} ${h*(.1+(seed%5)*.1)} ${w*.5} ${h*.5} T${w} ${h*.5} V${h} H0 Z" fill="url(#g)"/>`;
 if(action==='blob'){const points=Array.from({length:12},(_,i)=>{const angle=i*Math.PI/6;const r=.32+.08*Math.sin(i*2.7+seed);return `${w/2+Math.cos(angle)*w*r},${h/2+Math.sin(angle)*h*r}`;});content=`${defs}<polygon points="${points.join(' ')}" fill="url(#g)" stroke="${a}" stroke-width="${Math.min(w,h)*.07}" stroke-linejoin="round"/>`;}
 if(action==='pattern'){const size=20+(seed%8)*8;content=`<defs><pattern id="p" width="${size}" height="${size}" patternUnits="userSpaceOnUse"><rect width="${size}" height="${size}" fill="${b}"/><circle cx="${size/2}" cy="${size/2}" r="${size/5}" fill="${a}"/></pattern></defs><rect width="100%" height="100%" fill="url(#p)"/>`;}
 if(action==='spinner'){const r=Math.min(w,h)*.3;content=`<circle cx="${w/2}" cy="${h/2}" r="${r}" fill="none" stroke="${a}" stroke-width="${r/6}" stroke-dasharray="${r*4} ${r*3}"><animateTransform attributeName="transform" type="rotate" from="0 ${w/2} ${h/2}" to="360 ${w/2} ${h/2}" dur="${1+(seed%5)*.2}s" repeatCount="indefinite"/></circle>`;}
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${content}</svg>`;
}
export async function svgPng(source:string,w:number,h:number){const {c,ctx}=canvas2d(w,h);const url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('SVG could not be rendered. / SVG não pôde ser renderizado.'));image.src=url;});ctx.drawImage(image,0,0,w,h);return canvasBlob(c);}finally{URL.revokeObjectURL(url);}}
export async function svgEngine(action:string,text:string,files:File[],v:Values):Promise<Output[]>{let source:string;if(action==='trace'){const bitmap=await createImageBitmap(files[0]);try{const scale=Math.min(1,800/bitmap.width,800/bitmap.height);const {c,ctx}=canvas2d(Math.max(1,Math.round(bitmap.width*scale)),Math.max(1,Math.round(bitmap.height*scale)));ctx.drawImage(bitmap,0,0,c.width,c.height);const {default:tracer}=await import('imagetracerjs');source=safeSvg(tracer.imagedataToSVG(ctx.getImageData(0,0,c.width,c.height),{numberofcolors:number(v.colors,8,2,32),ltres:1,qtres:1}));}finally{bitmap.close();}}else if(['viewer','code','minify','to-png'].includes(action))source=safeSvg(text);else source=generatedSvg(action,v);
 if(action==='minify'){const {optimize}=await import('svgo/browser');source=optimize(source,{multipass:true}).data;}
 if(action==='to-png')return [{name:'image.png',blob:await svgPng(source,number(v.width,800,1,4096),number(v.height,600,1,4096)),preview:'image'}];return [{...textOutput(source,'design.svg','image/svg+xml'),preview:'image',note:['viewer','code','minify','to-png'].includes(action)?'Active content, styles and external resources are removed. / Conteúdo ativo, estilos e recursos externos são removidos.':undefined}];
}
