import { createHash, randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { accessContext, accessError, enforceRateLimit } from "@/lib/server/access";
import { database } from "@/lib/server/database";
const schema=z.object({email:z.string().email().max(254),role:z.enum(["owner","tester"]).default("tester"),creditLimit:z.number().int().min(1).max(100).default(5),expiresInHours:z.number().int().min(1).max(720).default(72)});
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function GET(req:Request){try{const access=await accessContext(req);if(access.role!=="admin") throw new Error("FORBIDDEN");const rows=await database()`select id,email,role,credit_limit,expires_at,accepted_at,revoked_at,created_at from pilot_invites order by created_at desc limit 100`;return NextResponse.json({success:true,invites:rows});}catch(error){const known=accessError(error);return NextResponse.json({success:false,error:known?.error||"Unable to list invites."},{status:known?.status||500});}}
export async function POST(req:Request){try{const access=await accessContext(req);if(access.role!=="admin") throw new Error("FORBIDDEN");await enforceRateLimit(access,"invites:create",10,60);const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({success:false,error:"Invalid invitation."},{status:400});const token=randomBytes(32).toString("base64url");const v=parsed.data;const [row]=await database()`insert into pilot_invites(email,token_hash,role,credit_limit,expires_at,created_by) values(${v.email.toLowerCase()},${hash(token)},${v.role}::app_role,${v.creditLimit},now()+(${v.expiresInHours}*interval '1 hour'),${access.userId}) returning id,expires_at`;return NextResponse.json({success:true,invite:{id:row.id,url:`${new URL(req.url).origin}/invite?token=${token}`,expiresAt:row.expires_at}},{status:201});}catch(error){const known=accessError(error);return NextResponse.json({success:false,error:known?.error||"Unable to create invite."},{status:known?.status||500});}}
export async function DELETE(req:Request){try{const access=await accessContext(req);if(access.role!=="admin") throw new Error("FORBIDDEN");const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({success:false,error:"Invite id is required."},{status:400});const rows=await database()`update pilot_invites set revoked_at=now() where id=${id} and accepted_at is null and revoked_at is null returning id`;return NextResponse.json({success:rows.length===1},{status:rows.length?200:404});}catch(error){const known=accessError(error);return NextResponse.json({success:false,error:known?.error||"Unable to revoke invite."},{status:known?.status||500});}}
